### ISSUE TITLE
Add DiTing: A large-scale Chinese seismic benchmark dataset

### ISSUE THREAD

**Issue by yetinam** [seisbench/seisbench#103]
I just stumbled across this dataset, which I think would be a great addition to SeisBench. This bug is mostly for tracking the general interest in adding the dataset. Anyone interested in working on this is very welcome to do so.

https://www.equsci.org.cn/article/id/c8dc6e48-348f-4224-a9fc-6cc333f3109e?pageType=en

**Comment by MrXiaoXiao** [comment]
I would like to help add the DiTing dataset to SeisBench. I've been busy recently, but I will try to finish seisbench/data/diting.py and open a pull request before the end of this month.

**Comment by yetinam** [comment]
Hey @MrXiaoXiao ,
thanks for volunteering! Looking forward to your PR. If you have any questions, feel free to ask them here in this thread.

**Comment by MrXiaoXiao** [comment]
Sorry that I failed to finish the PR in July. I will need two more weeks to add DiTing dataset to Seisbench.

**Comment by yetinam** [comment]
Thanks for the heads-up! No worries, the contribution is still warmly welcomed in the next weeks.

**Comment by yetinam** [comment]
After personal communications with the authors, there are currently no ways planned for sharing the dataset internationally. Therefore, I'm closing the issue.
