### ISSUE TITLE
Is there any example about training Deepnoise models on seismic data?

### ISSUE THREAD

**Issue by ZZYBian** [seisbench/seisbench#104]
Hi all

Thank you very much for providing such a useful ML tool.  Is there any example of training Deepnoise models on seismic data?
I want to train the pre-trained model using local data.

**Comment by yetinam** [comment]
Hi @ZZYBian ,
Unfortunately, we have never trained DeepDenoiser ourselves. The two sets of pretrained weights are converted from the original publications. However, we'd be happy to include further weights and an example for training if you'd build this.

**Comment by yetinam** [comment]
Closing this issue for now, but feel free to reopen if you have further questions.
