### ISSUE TITLE
Re: Problem with predictions

### ISSUE THREAD

**Issue by sfpoveda** [seisbench/seisbench#106]
Hi, 

I'm again. Just that I did what you suggested me and I keep getting the same result "0 Trace(s) in Stream". Below, I attached an image of my code and other things so that you can indicate me, please, what is wrong with my implementation. I tried with PhaseNet, EQTransformer and GPD models, and in all models I used "stead" pre-trained weights dataset. I think the format is not the problem because I have tried with SAC and MSEED formats and with both I obtained the same results.

<img width="621" alt="Capture3" src="https://user-images.githubusercontent.com/93283899/175187098-a334aa02-f47a-4ace-9888-8d74e480798a.PNG">

**Comment by yetinam** [comment]
Hi, sorry, I noticed I made a bad typo in the other issue reply. It needs to be `strict=False`. I fixed it in the other issues as well now, in case people will use it for further reference.

**Comment by sfpoveda** [comment]
It works now. Thank you!

**Comment by sfpoveda** [comment]
On the same way. To use the command "classify" instead of the command "annotate", there is other important parameter we should take into account? Because I tried using "classify(stream, strict=False)" and the lists are empty. I think it could be so because classify is not able to detect the picks despite it is working, but I want to be sure. One should expect to obtain the same results (picks) using the method "annotate" as well as using the method "classify"?

**Comment by yetinam** [comment]
@sfpoveda Could you quickly confirm whether your question is solved and close the issue in that case?

**Comment by sfpoveda** [comment]
Yes, you did. Question solved, thanks.
