### ISSUE TITLE
original deep network of Phasenet

### ISSUE THREAD

**Issue by javak87** [seisbench/seisbench#107]
Dear Developer,
I want to use original deep network of the Phasenet, but it is not included in seisbench package. Here the message:
-------------------------------------------------------------------------------------------------------------------------------
model = sbm.PhaseNet.from_pretrained("original")
print(model.weights_docstring)
------------------------------------------------------------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/home/javak/Transfer-Deep-Learning-chile-subduction-zone/seisbench-examples/01b_model_api.ipynb Cell 18' in <cell line: 1>()
----> [1](vscode-notebook-cell:/home/javak/Transfer-Deep-Learning-chile-subduction-zone/seisbench-examples/01b_model_api.ipynb#ch0000017?line=0) model = sbm.PhaseNet.from_pretrained("original")
      [2](vscode-notebook-cell:/home/javak/Transfer-Deep-Learning-chile-subduction-zone/seisbench-examples/01b_model_api.ipynb#ch0000017?line=1) print(model.weights_docstring)

File ~/miniconda3/envs/seisbench/lib/python3.10/site-packages/seisbench/models/base.py:173, in SeisBenchModel.from_pretrained(cls, name, version_str, update, force, wait_for_file)
    170         versions = cls.list_versions(name, remote=True)
    172     if len(versions) == 0:
--> 173         raise ValueError(f"No version for weight '{name}' available.")
    174     version_str = max(versions, key=version.parse)
    176 weight_path, metadata_path = cls._pretrained_path(name, version_str)

ValueError: No version for weight 'original' available.
-------------------------------------------------------------------------------------------------------------------------------------
As you can see there is no original model related to the PhaseNet.
Could you please provide this model in this package?
Best regards,
Javad

**Comment by yetinam** [comment]
Hey @javak87 ,
thanks for your interest in SeisBench. Unfortunately, we do not currently have the original PhaseNet weights included in SeisBench. As the original model is written in tensorflow and none of the core developers is very experienced with this framework, it would take us quite some time to do the conversion and I don't think we'll tackle this anytime soon. However, if you'd like to do the conversion and contribute the weights to SeisBench that would be very welcome.

**Comment by javak87** [comment]
Dear @yetinam,
Thank you for your information.
In the following months, if I convert TensorFlow into PyTorch, I will let you know.
Best regards,
Javad
