### ISSUE TITLE
Tensor dimensions problem when training BasicPhaseAE model

### ISSUE THREAD

**Issue by sfpoveda** [seisbench/seisbench#109]
Hi everyone,

I'm having some problems trying to train a BasicPhaseAE model with my own data. I get the following error:
![image](https://user-images.githubusercontent.com/93283899/176979501-d525589d-9ae6-48c1-a66e-a77aedac56f8.png)
As you can see the input data (batch['X']) has dimensions ([128, 1, 3000]) so when I put that input data in model I should obtain a tensor (pred tensor) of equal dimensions, right? But instead of that, what I obtain is a tensor of dimensions ([128, 1, 3450]). Do you have any idea of where could come that 450 (3450 - 3000) extra points? 

The problem of dimensions appears to be solved when I run the code with the default parameter "in_samples=600", but when I try to change the "in_samples" parameter (e.g. in_samples=3000), the above error comes on. What do you think is the reason why this happens? 
![image](https://user-images.githubusercontent.com/93283899/176979872-fec07ae8-caff-4b66-b63a-5926722e5b58.png)

Below you find a copy of the code I'm running if necessary:
![image](https://user-images.githubusercontent.com/93283899/176979912-7ff2f98a-d475-4a6d-a6fd-67cdadc8516d.png)
![image](https://user-images.githubusercontent.com/93283899/176979955-fba26345-0974-4c3f-a76b-8d55d4013c2e.png)

![image](https://user-images.githubusercontent.com/93283899/176979993-6ee4e378-14a6-4dbc-8261-14f252f107f7.png)

Sorry for the long text, and thanks, I really appreciate this space for doubts.

**Comment by yetinam** [comment]
Hi @sfpoveda ,

Thanks for reporting the issue. In principle, this will be caused by padding artifacts, i.e., length differences due to added or removed samples at the boundaries. I think it would be a nice addition, if this would automatically be handled. Would you like to prepare a PR on this? Alternatively, I guess we should at least add a warning when creating the model with the non-standard number of samples.

However, in general, I'd discourage the use of BasicPhaseAE. From our benchmark, it was always outperformed by PhaseNet, which in addition has a very similar architecture. Do you have a specific reason for using BasicPhaseAE?

**Comment by sfpoveda** [comment]
Thnaks for solving my doubt! 
I do not have any special reason for using BasicPhaseAE, I was just testing the different models available in Seisbench to evaluate their performing on the same data. By the way: There is something important to know before trying to train the other available models (DPP, GPD and EQTransformer) ? What do you think about the performing of EQTransformer compared to the performing of PhaseNet? I think these two models are the best based on some applied pickings I made, but I would like to read your point of view about this two models 

Note: What means the "PR" abbreviation?

**Comment by yetinam** [comment]
In general, all of the models have very similar interfaces, so they can be trained the same way. However, some of the models suggest to use some data augmentation. Best starting point for training is probably our [benchmark repository](https://github.com/seisbench/pick-benchmark). You can check the `get_augmentations` functions for the different models [here](https://github.com/seisbench/pick-benchmark/blob/main/benchmark/models.py), which will show you the configurations we used for training.

Regarding performance, we saw very similar performance for PhaseNet and EQTransformer in our benchmark. EQTransformer seems to have some advantages on lower-period signals, e.g., teleseismic arrivals. However, whether there would be a larger difference when applied to continuous data is yet to be answered.

PR stands for "pull request", i.e., suggested code contributions. Sorry for the use of jargon here. The PRs are listed [here](https://github.com/seisbench/seisbench/pulls?q=is%3Apr+is%3Aclosed) (currently there is no open PR, so you have to look at the closed ones).
