### ISSUE TITLE
Creating a seisbench dataset for Botswana and South Africa

### ISSUE THREAD

**Issue by maritinkolej** [seisbench/seisbench#113]
I am following an example under seisbench tutorial for creating dataset using ETHZ dataset and everything works well. Now when I use my custonm region something goes wrong. First of all I use catalogue from ISC and download corresponding waveforms from IRIS. 
I notice that ISC cataloque use the network code "IR" for all events which is not = FDSN network code. After getting some assistance from Obspy forum, I modify the code by adding the following in order to download waveforms from BX network at IRIS.

client = Client('IRIS')
inv = client.get_stations(network='BX', level='station')
sta_codes_bx = [sta.code for net in inv for sta in net]

#for pick in event.picks:
for event in cat:
    for pick in event.picks:
        is_IR = pick.waveform_id.network_code == 'IR'
        should_be_BX = pick.waveform_id.station_code in sta_codes_bx
        if is_IR and should_be_BX:
            pick.waveform_id.network_code = 'BX'

After modification, the csv and hdf5 is downloaded but it is not working when trying to train EQTransformer. It looks like the problem is with my csv file. 

[Test.csv](https://github.com/seisbench/seisbench/files/9116502/Test.csv)

I am wondering where the problem is because I am a newbie. I am a Masters' student doing a research aiming to retrain EQTranformer and then perform phase picking using the retrained model. 
I wish to send the whole code I am using so that you can check where I went wrong, but the attachment does not allow the format type of ipynb. I have attached the csv file above.

**Comment by yetinam** [comment]
Hey @maritinkolej ,
thanks for your interest in SeisBench! I had a quick look at the csv file and could not spot an obvious error. Could you provide the error traceback when you try using the dataset to train an EQTransformer model?

As a side note, you might have a look at this code [implementing the ETHZ dataset](https://github.com/seisbench/seisbench/blob/main/seisbench/data/ethz.py). It is a bit more comprehensive than the example in the notebook.

**Comment by maritinkolej** [comment]
I am getting this error: 'NoneType' object has no attribute 'attrs'. 

I am also going through the comprehensive code you sent me, If I encounter any problems I will communicate. Honestly, I am a newbie so it takes me some time to understood, however I commit myself to go through it and understand it and try with my data of interest.

**Comment by yetinam** [comment]
Thanks for the update. To understand the issue, we'll need to full error traceback output by python, i.e., including the line number of where the error is happening. In addition, could you provide the version number of SeisBench you are using? Once you imported SeisBench, the version number can be determined using `seisbench.__version__`.

**Comment by yetinam** [comment]
Thanks for providing the trace. I think the error results from a misunderstanding. As far as I see, you try using the dataset with the original EQTransformer implementation. SeisBench datasets are **not compatible** with the original EQTransformer implementation. We also currently have no plans to add this support. However, there is an implementation of EQTransformer within SeisBench that can be trained using SeisBench. Check out the "Training PhaseNet" notebook for a quick intro on how to train PhaseNet. The training for EQTransformer can be set up similarly. For an example, have a look at our [benchmark repository](https://github.com/seisbench/pick-benchmark).

I hope this answer helps with your question. Feel free to ask further questions in this thread or close the issue if your question is resolved.

**Comment by maritinkolej** [comment]
I am getting this error with the waveforms and metadata I am using when I try to run my data training PhaseNet

ValueError                                Traceback (most recent call last)
<ipython-input-28-f1b454d97dd6> in <module>
      1 data = sbd.ETHZ(sampling_rate=100)
----> 2 train, dev, test = data.train_dev_test()

~/.local/lib/python3.8/site-packages/seisbench/data/base.py in train_dev_test(self)
    824         :return: Training dataset, development dataset, test dataset
    825         """
--> 826         return self.train(), self.dev(), self.test()
    827 
    828     def _evict_cache(self):

~/.local/lib/python3.8/site-packages/seisbench/data/base.py in train(self)
    798         :return: Training dataset
    799         """
--> 800         return self.get_split("train")
    801 
    802     def dev(self):

~/.local/lib/python3.8/site-packages/seisbench/data/base.py in get_split(self, split)
    786         """
    787         if "split" not in self.metadata.columns:
--> 788             raise ValueError("Split requested but no split defined in metadata")
    789 
    790         mask = (self.metadata["split"] == split).values

ValueError: Split requested but no split defined in metadata

**Comment by maritinkolej** [comment]
I managed to train the PhaseNet successfully using my data. I fixed the issue above.
