### ISSUE TITLE
Dataset download error

### ISSUE THREAD

**Issue by LuYijing1** [seisbench/seisbench#116]
`2022-07-24 18:00:39,662 | seisbench | WARNING | Check available storage and memory before downloading and general use of Iquique dataset. Dataset size: waveforms.hdf5 ~5Gb, metadata.csv ~2.6Mb
2022-07-24 18:00:41,448 | seisbench | WARNING | Dataset Iquique not in cache.
2022-07-24 18:00:41,449 | seisbench | WARNING | Trying to download preprocessed version from SeisBench repository.
Downloading metadata: 100%|██████████| 2.57M/2.57M [00:00<00:00, 2.88MB/s]
Downloading waveforms:  22%|██▏       | 1.11G/4.98G [10:00<34:53, 1.98MB/s]   
Output exceeds the size limit. Open the full output data in a text editor
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/tmp/ipykernel_522/3705471254.py in <module>
      1 #data = sbd.ETHZ(sampling_rate=100)
----> 2 data = sbd.Iquique(sampling_rate=100)

~/miniconda3/envs/seis1/lib/python3.7/site-packages/seisbench/data/iquique.py in __init__(self, **kwargs)
     27         )
     28 
---> 29         super().__init__(citation=citation, repository_lookup=True, **kwargs)
     30 
     31     def _download_dataset(**kwargs):

~/miniconda3/envs/seis1/lib/python3.7/site-packages/seisbench/data/base.py in __init__(self, chunks, citation, license, force, wait_for_file, repository_lookup, download_kwargs, **kwargs)
   1797             )
   1798 
-> 1799         super().__init__(path=None, name=self._name_internal(), chunks=chunks, **kwargs)
   1800 
   1801     @property

~/miniconda3/envs/seis1/lib/python3.7/site-packages/seisbench/data/base.py in __init__(self, path, name, dimension_order, component_order, sampling_rate, cache, chunks, missing_components, **kwargs)
    135         self._metadata = pd.concat(metadatas)
    136 
--> 137         self._data_format = self._read_data_format()
    138 
...
h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (truncated file: eof = 1191968768, sblock->base_addr = 0, stored_eof = 5347073704)`

The above error occurs every 10 minutes when downloading data. We have tried changing the network, but the problem still occurs at 10 minutes of downloading, is there any way to fix it?

**Comment by yetinam** [comment]
Hey @LuYijing1 ,
thanks for reporting the issue. This is indeed curious behaviour and seems to be related to the underlying environment. Could you give me more details on your setup? Which python version are you using, which version of SeisBench and are you using seisbench within a script or an interactive session (ipython or jupyter notebook)?

**Comment by LuYijing1** [comment]
Thank you very much for your reply, I am using python version 3.7.13 and seisbench version 0.2.4, I am using seisbench in jupyter.

**Comment by yetinam** [comment]
Looking at the trace, I think there might be a combination of two issues. First, something terminates the download. This might be either jupyter or the operating system of your machine. Can you run longer downloads, e.g., using wget on the same machine? Second, the error is not correctly handled in SeisBench, leading to the crash at a slightly later point. We should have a look at this.

**Comment by LuYijing1** [comment]
OK! Thanks!
