### ISSUE TITLE
Merging Dataset

### ISSUE THREAD

**Issue by maritinkolej** [seisbench/seisbench#117]
Is there a code I can use to merge two seisbench dataset from different regions. My dataset is converted to seisbench format but it is not enough.

**Comment by yetinam** [comment]
Hey @maritinkolej ,
it depends a bit on your use case. If it's sufficient for you just to load the parts separately and merge them once loaded, you can just use `dataset1 + dataset2`. If you want to write the dataset to disk, you'll have to iterate over this sum and write out the new dataset. An example for this kind of transcoding a dataset is available [here](https://github.com/seisbench/seisbench/blob/main/contrib/transcode_dataset.py). The input in the example is not a sum of datasets, but that should be quick to swap out.

**Comment by maritinkolej** [comment]
The information helps, thank you.
