### ISSUE TITLE
Save data and model repository to local machine.

### ISSUE THREAD

**Issue by DDEssing** [seisbench/seisbench#119]
Hello everyone,

I am having the issue that my institute has not opened the required port to load the data and model repository. As it works fine for me back home I was wondering whether I can load it back home and save it locally to eventually use it also at work?

Anyway, thank you so much for this great project!

**Comment by yetinam** [comment]
Hey @DDEssing,

thanks for reporting this. Indeed, you can transfer your local SeisBench repository between machines. By default, it is located at `%HOME/.seisbench`, but you can also determine your path using `python -c "import seisbench;print(seisbench.cache_root)"`.

If it's more convenient for you to download the files through other means (browser/wget/...), you can access them directly at https://dcache-demo.desy.de:2443/Helmholtz/HelmholtzAI/SeisBench/.

Out of curiosity, which institution are you at and did you ask your IT department if it would be possible to allow accesses to this port? This would be interesting for us to assess the general scope of the problem.
