### ISSUE TITLE
Problems training CRED

### ISSUE THREAD

**Issue by aacofre** [seisbench/seisbench#120]
Dear Developer,
I want to train CRED model with other databases. But I get an input dimension error (at least with ETHZ and Iquique, which I have tested)
I followed your example in colab, and I always get the same error; I don't know if I should add one more step or if I'm doing something wrong. I would appreciate the help.

error: **"RuntimeError: Expected 4-dimentional input for 4-dimensional weight [8, 3, 9, 9], but got 3-dimensional input of size [256, 3, 3001] instead"**

**Comment by yetinam** [comment]
Hi @aacofre ,
Thanks for the question. CRED requires a different input format. This can be achieved by modifying the set of augmentations. Here is an example from our benchmark study: https://github.com/seisbench/pick-benchmark/blob/2fae5941f632fb2146e6bea37f94eb89a2c89bc7/benchmark/models.py#L621 . I hope this helps solving your problem.
