### ISSUE TITLE
error when using "sbm.EQTransformer.from_pretrained('original', version_str='1')" on the current latest SeisBench version (0.2.4)

### ISSUE THREAD

**Issue by speedshi** [seisbench/seisbench#122]
After I updated to the SeisBench version of '0.2.4',  errors occur when I try to use the pre-trained EQT model of versions 1 and 2.
for example:
import seisbench.models as sbm
model = sbm.EQTransformer.from_pretrained('original', version_str='1')  will give me the error as below:

**_Traceback (most recent call last):
  File "P01_use_seisbench_picking.py", line 31, in <module>
    model = sbm.EQTransformer.from_pretrained(pre_trained, version_str='1')  # specify a ML model for prediction 
  File "/home/shipe/anaconda3/envs/seisbench/lib/python3.7/site-packages/seisbench/models/base.py", line 182, in from_pretrained
    return cls.load(weight_path.with_name(name), version_str=version_str)
  File "/home/shipe/anaconda3/envs/seisbench/lib/python3.7/site-packages/seisbench/models/base.py", line 478, in load
    model.load_state_dict(model_weights)
  File "/home/shipe/anaconda3/envs/seisbench/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for EQTransformer:
	Missing key(s) in state_dict: "pick_lstms.0.weight_ih_l0", "pick_lstms.0.weight_hh_l0", "pick_lstms.0.bias_ih_l0", "pick_lstms.0.bias_hh_l0", "pick_lstms.1.weight_ih_l0", "pick_lstms.1.weight_hh_l0", "pick_lstms.1.bias_ih_l0", "pick_lstms.1.bias_hh_l0". 
	Unexpected key(s) in state_dict: "pick_lstms.0.cell_f.weight_ih", "pick_lstms.0.cell_f.weight_hh", "pick_lstms.0.cell_f.bias_ih", "pick_lstms.0.cell_f.bias_hh", "pick_lstms.1.cell_f.weight_ih", "pick_lstms.1.cell_f.weight_hh", "pick_lstms.1.cell_f.bias_ih", "pick_lstms.1.cell_f.bias_hh"._**

Is there anything I am not using correctly? Or there is a bug in the code?

Best regards.

**Comment by yetinam** [comment]
Hi @speedshi ,
thanks for your report. Indeed, versions "1" and "2" are incompatible with seisbench>=0.2.3. This is also noted in our [known issues](https://github.com/seisbench/seisbench#known-issues). Is there a specific reason why you would like to use those versions? Version 2 and 3 are semantically identical and version 1 only differs by a missing highpass filter. All three versions use the same set of weights. If you absolutely require version 1 or 2, I'd for now recommend downgrading to seisbench 0.2.2.

**Comment by speedshi** [comment]
Hi @yetinam ,

Thanks a lot for your reply. Previously, I thought these models are essentially different and generated by different training processes, so want to test to on my dataset to find a better one. If there are the same, I can just use the latest one.

But I would suggest taking the filtering processes out of the model and letting the user choose the filtering band (like the other models). Because I notice sometimes the performance can vary a lot on different frequency bands, and the optimal frequency ranges are not always the same.

**Comment by yetinam** [comment]
Great, thanks for the update! Regarding the suggestion, we integrated the filter as for the "original" model, we try to reproduce as closely as possible the behaviour of the model by Mousavi et al. However, we're working on improving the documentation on this part so that it's easier to spot how to deactivate it.
