### ISSUE TITLE
Acknowledging institutions/infrastructure in the README

### ISSUE THREAD

**Issue by yetinam** [seisbench/seisbench#132]
Currently, there is no point in the SeisBench repository, where we acknowledge the institutions involved or the infrastructure provider (HIFIS). On one hand, this makes SeisBench seem very open, on the other hand, it's maybe not quite fair towards these institutions. My suggestion would be to add a "Supporters" heading to the end of the README and insert a few logos.

The following institutions might be reasonable to acknowledge:
- HIFIS (for providing the infrastructure)
- GFZ and KIT (as the initial institutions)
- the current (and past?) institutions of all maintainers (i.e., at the moment UGA, GFZ and KIT)

What's your opinion on the matter? How should we acknowledge and in what form? In particular, which of the institutions above should we acknowledge?

**Comment by jawooll** [comment]
Hey Jannes, I think this is a good idea from my side and makes complete sense 👍

**Comment by yetinam** [comment]
Hi @jawooll,
thanks for the quick reply. I just updated my comment above to add the question which institutions we should acknowledge. Could you add your opinion on that question?

**Comment by jawooll** [comment]
Ah sorry yeah got it! Before including my opinion, I'll just add that maybe Frederik and Andreas would be better placed to 'green light' this as respective drivers of the project from the different institutions. From my side, I think adding to the README as you describe is sufficient. We could also include the same information in the documentation, adding a section to the landing page.
