### ISSUE TITLE
Style of Adding Gaussian Noise when augmenting training datasets

### ISSUE THREAD

**Issue by JUNZHU-SEIS** [seisbench/seisbench#137]
In seisbench, adding noise is simply achieved through
```
scale = np.random.uniform(*self.scale) * np.max(x)
noise = np.random.randn(*x.shape).astype(x.dtype) * scale
```
Different from EQTransformer, which construct Gaussian noise for individual component one by one.

Is there any difference between them in synthesizing noise? In my view, EQT's way seems more close to reality.

**Comment by yetinam** [comment]
Hi,

indeed, there is a small difference with respect to the scale. In [EQTransformer](https://github.com/smousavi05/EQTransformer/blob/27511f8dea85d30f0f60879d182a0b8455b1d38e/EQTransformer/core/EqT_utils.py#L225) the scales are taken separately for each component. SeisBench in contrast takes the same scale for all axis. In both cases, the generated noise is fully independent between components.

I personally think a uniform noise scaling across components might be more natural, but maybe we should just add an option for the users to choose. Should be a fairly small change.
