### ISSUE TITLE
seisbench-cpu

### ISSUE THREAD

**Issue by niyiyu** [seisbench/seisbench#138]
Hi!

I've been working on deploying ML phase picking on the cloud at scale. The project repo is [here](https://github.com/Denolle-Lab/seismicloud). I have noticed that using GPU for containerized task made configuration somehow complicated and decided to just using CPU. The potential advantages and disadvantages are:
- CPU instances on the cloud are usually much cheaper than GPU instance, and easier to deploy
- get rid of CUDA toolkits, which should dramatically reduce the size of docker image
- slow down the workflow by 4-10 times, but we can add much more CPU cores very flexibly

However, seems CUDA toolkits may not be easily removed from seisbench. Do you think we can have a simplified torch-CPU version as an individual branch?

Thanks,
Yiyu

**Comment by niyiyu** [comment]
Hmm, I misunderstand one point. If I choose pytorch-cpu, then seisbench is just CPU. On the other hand, pytorch-gpu requires CUDA toolkit. So only one branch works. Closing this issue. Feel free to take a look at our efforts of deploying seisbench on the cloud. : )

**Comment by yetinam** [comment]
Hey @niyiyu iyiyu,

thanks for the sharing your code. It's really cool to see what you have built. Can you give some indication how far you have scaled up?

Regarding the original question, I am surprised that pytorch by default comes with CUDA dependencies. I though that just `pip install pytorch` should not try installing CUDA. And similarly, as long as you don't actively call `model.cuda()`, SeisBench should keep all the processing on CPU. If the `pytorch` package comes with a CUDA dependency, it might actually be worthwhile to create an additional `seisbench-cpu` package on PyPI.

**Comment by niyiyu** [comment]
Hey @yetinam 

Thanks for replying. Here are some test of installing PyTorch through `conda` and `pip`
1. `conda install -c conda-forge pytorch`
```     
Collecting package metadata (current_repodata.json): done
Solving environment: done

    package                    |            build
    ---------------------------|-----------------
    cffi-1.15.1                |   py38h4a40e3a_2         229 KB  conda-forge
    cudatoolkit-11.7.0         |      hd8887f6_10       831.6 MB  conda-forge
    cudnn-8.4.1.50             |       hed8a83a_0       618.4 MB  conda-forge
    intel-openmp-2022.1.0      |    h9e868ea_3769         4.5 MB
    libblas-3.9.0              |16_linux64_openblas          13 KB  conda-forge
    libcblas-3.9.0             |16_linux64_openblas          13 KB  conda-forge
    libgfortran-ng-12.2.0      |      h69a702a_19          22 KB  conda-forge
    libgfortran5-12.2.0        |      h337968e_19         1.8 MB  conda-forge
    liblapack-3.9.0            |16_linux64_openblas          13 KB  conda-forge
    libopenblas-0.3.21         |pthreads_h78a6416_3        10.1 MB  conda-forge
    libprotobuf-3.21.9         |       h6239696_0         2.5 MB  conda-forge
    libstdcxx-ng-12.2.0        |      h46fd767_19         4.3 MB  conda-forge
    magma-2.5.4                |       hc72dce7_4       106.8 MB  conda-forge
    mkl-2022.1.0               |     hc2b9512_224       129.7 MB
    nccl-2.14.3.1              |       h0800d71_0       145.2 MB  conda-forge
    ninja-1.11.0               |       h924138e_0         2.8 MB  conda-forge
    numpy-1.23.4               |   py38h7042d01_1         7.1 MB  conda-forge
    pytorch-1.12.1             |cuda112py38hd94e077_201       490.5 MB  conda-forge
    sleef-3.5.1                |       h9b69904_2         1.5 MB  conda-forge
    typing_extensions-4.4.0    |     pyha770c72_0          29 KB  conda-forge
    zlib-1.2.13                |       h166bdaf_4          92 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        2.30 GB
```
So cudatoolkit and cudnn would be installed by default as GPU version is the default release from conda-forge channel. 


2. `pip install torch` 
```
Collecting torch
  Using cached torch-1.13.0-cp38-cp38-manylinux1_x86_64.whl (890.2 MB)
Collecting nvidia-cudnn-cu11==8.5.0.96
  Using cached nvidia_cudnn_cu11-8.5.0.96-2-py3-none-manylinux1_x86_64.whl (557.1 MB)
Collecting nvidia-cuda-runtime-cu11==11.7.99
  Using cached nvidia_cuda_runtime_cu11-11.7.99-py3-none-manylinux1_x86_64.whl (849 kB)
Collecting nvidia-cuda-nvrtc-cu11==11.7.99
  Using cached nvidia_cuda_nvrtc_cu11-11.7.99-2-py3-none-manylinux1_x86_64.whl (21.0 MB)
Collecting nvidia-cublas-cu11==11.10.3.66
  Using cached nvidia_cublas_cu11-11.10.3.66-py3-none-manylinux1_x86_64.whl (317.1 MB)
Collecting typing-extensions
  Using cached typing_extensions-4.4.0-py3-none-any.whl (26 kB)
```
So the same for `pip`. Thus `pip install seisbench` would also pull CUDA due to the dependency relation.

3. `conda install -c conda-forge pytorch-cpu`
```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cffi-1.15.1                |   py38h4a40e3a_2         229 KB  conda-forge
    intel-openmp-2022.1.0      |    h9e868ea_3769         4.5 MB
    libblas-3.9.0              |16_linux64_openblas          13 KB  conda-forge
    libcblas-3.9.0             |16_linux64_openblas          13 KB  conda-forge
    libgfortran-ng-12.2.0      |      h69a702a_19          22 KB  conda-forge
    libgfortran5-12.2.0        |      h337968e_19         1.8 MB  conda-forge
    liblapack-3.9.0            |16_linux64_openblas          13 KB  conda-forge
    libopenblas-0.3.21         |pthreads_h78a6416_3        10.1 MB  conda-forge
    libprotobuf-3.21.9         |       h6239696_0         2.5 MB  conda-forge
    libstdcxx-ng-12.2.0        |      h46fd767_19         4.3 MB  conda-forge
    mkl-2022.1.0               |     hc2b9512_224       129.7 MB
    ninja-1.11.0               |       h924138e_0         2.8 MB  conda-forge
    numpy-1.23.4               |   py38h7042d01_1         7.1 MB  conda-forge
    pytorch-1.12.1             |cpu_py38h23e632a_1        64.9 MB  conda-forge
    pytorch-cpu-1.12.1         |cpu_py38h587aeda_1          21 KB  conda-forge
    sleef-3.5.1                |       h9b69904_2         1.5 MB  conda-forge
    typing_extensions-4.4.0    |     pyha770c72_0          29 KB  conda-forge
    zlib-1.2.13                |       h166bdaf_4          92 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       229.6 MB
```
Explicit specifying `pytorch-cpu` skips pulling CUDA.

4. `pip install torch --extra-index-url https://download.pytorch.org/whl/cpu` following [link](https://pytorch.org/get-started/locally/)
```
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cpu
Collecting torch
  Downloading https://download.pytorch.org/whl/cpu/torch-1.13.0%2Bcpu-cp38-cp38-linux_x86_64.whl (198.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 198.5/198.5 MB 15.0 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions in ./anaconda3/envs/tmp/lib/python3.8/site-packages (from torch) (4.4.0)
Installing collected packages: torch
Successfully installed torch-1.13.0+cpu
```

I think it is reasonable to have a `seisbench-cpu` as a separate branch or repo. I think a branch might make things easier with just a different requirement.txt file which explicitly use torch cpu. But for now, I am not sure how to pass `--extra-index-url https://download.pytorch.org/whl/cpu` to the requirement file. I'm re-opening this issue for more discussion.

Regarding my case of creating a docker image, explicitly specifying pytorch-cpu in the [environment file](https://github.com/Denolle-Lab/seismicloud/blob/main/environment.yml) and remove CUDA in the [Docker file](https://github.com/Denolle-Lab/seismicloud/blob/63795e136cd915e1736181f5cef4069876ce3969/Dockerfile#L11) skips the installation of CUDA tool kit and reduced the size of image by 60%.

Yiyu

**Comment by yetinam** [comment]
Thanks for the comprehensive report. I'll experiment myself a little further out of curiosity but you've conclusively shown that seisbench automatically pulls CUDA. I think the easiest option will be to extend the CI script we use for publishing versions to automatically publish an additional seisbench-cpu package. I'll look into setting this up next week.

@jawooll : As this is a somewhat major decision, I quickly wanted to run it by you. Do you agree with what I'm suggesting?

**Comment by jawooll** [comment]
@yetinam Sounds good 👍  I think this seems the most reasonable approach. I'm also surprised that GPU + CUDA options are now the default. @niyiyu thanks for flagging this, and for the extensive documentation/reporting.

**Comment by yetinam** [comment]
I've now looked into this a bit. I think there is no option to install pytorch without CUDA through pip except specifying the URL. However, PyPI does not accept packages that put URLs into dependencies, i.e., we can't put seisbench-cpu on PyPI. I think the better option would be to also offer seisbench through conda. Then we could create a cpu and a gpu version there, which would be supported by pytorch. However, this will clearly be a bit more work.

**Comment by niyiyu** [comment]
@yetinam The seisbench requires torch>=1.7.0 and usually the latest version is installed (currently 1.13.0). I tested installing torch v1.12.1 and v1.13.0 using pip under py37, py38, py39, and py310: all v1.13.0 installed CUDA/cudnn while all v1.12.1 did not. So I checked the dependencies for [torch==1.13.0](https://pypi.org/pypi/torch/1.13.0/json) and [torch==1.12.1](https://pypi.org/pypi/torch/1.12.1/json).

torch-1.13.0
```
"requires_dist": [
    "typing-extensions",
    "nvidia-cuda-runtime-cu11 (==11.7.99)",
    "nvidia-cudnn-cu11 (==8.5.0.96)",
    "nvidia-cublas-cu11 (==11.10.3.66)",
    "nvidia-cuda-nvrtc-cu11 (==11.7.99)",
    "opt-einsum (>=3.3) ; extra == 'opt-einsum'"
]
```
torch-1.12.1
```
"requires_dist": [
    "typing-extensions",
]
```
Seems torch add dependency for CUDA since 1.13.0. If that's the case, we could freeze the seisbench's torch dependency before 1.13.0 if we want a cpu version. Hopefully this helps a little bit.

**Comment by yetinam** [comment]
Great catch! Interestingly I checked the release notes for pytorch 1.13.0 and didn't find any note of the newly added dependency. But to be fair, the release notes are very long so I might have just missed it.

Based on your finding I figured out that you can install a pure CPU version using `pip install pytorch~=1.12 seisbench`. As it seems a bit hacky to create a package that explicitly depends on an old version of pytorch, I'll do the following:
- add a note to the installation instructions on how to install a pure CPU version.
- create a new tracking bug for creating conda packages for seisbench that come in both a GPU and a CPU flavour
