### ISSUE TITLE
SteerGenerator doesn't return any sample in the example `01c_generator_pipelines.ipynb`

### ISSUE THREAD

**Issue by zhong-yy** [seisbench/seisbench#150]
Hi, thank you for providing such a well designed toolbox. 

I encountered a strange problem when I was running the example `01c_generator_pipelines.ipynb`. In the **Steered generators** section, `generator[0]` just returns `None`,  and after running the last cell, I got an error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[153], line 4
      1 sample = generator[0]
      2 print(sample)
----> 4 plt.plot(sample["X"].T)

TypeError: 'NoneType' object is not subscriptable
```
Why would this happen?

Here is a minimal working example:
```python
import seisbench.data as sbd
import seisbench.generate as sbg
import pandas as pd

data = sbd.ETHZ(sampling_rate=100)


control = []
for i in range(200):
    row = data.metadata.iloc[i]
    control_row = {"trace_name": row["trace_name"],
                   "start_sample": 1000,
                   "end_sample": 2000}
    control.append(control_row)

control = pd.DataFrame(control)

generator = sbg.SteeredGenerator(data, control)
print(generator[0])
```
Then generator[0] returns None

**Comment by yetinam** [comment]
Hi @zhong-yy ,
that's indeed weird and seems like a bug. I'll have a look at it in the next days.

**Comment by zhong-yy** [comment]
> Hi @zhong-yy , thanks for reporting the issue! That's indeed weird and seems like a bug. I'll have a look at it in the next days.

The example works well in seisbench 0.1.16 installed with pip.

**Comment by yetinam** [comment]
Turns out a recent refactor was missing a return statement and there was no test to catch that. I fixed it now.

Regarding the version number, the version number on our `main` branch should not be trusted. I've opened #159 to find a better strategy to deal with this.
