### ISSUE TITLE
question about creating a dataset 

### ISSUE THREAD

**Issue by Koushesh** [seisbench/seisbench#152]
Hi everyone there, 

I want to create a dataset using my internal detection-list/catalog. My catalog is currently in format of VELEST output like:

171001 0520  0.12 50.4353N   7.3144E  11.23   0.00    150      0.08
AHRWP4  1.58LAGBP1  3.44DP12P0  3.02OCHTP1  2.78BIW P2  7.94FACHP2  8.44
DP02S3  3.51OCHTS0  4.60BHE S1  5.33LAGBS0  5.67AHRWS4  4.03DP07S3 10.35
BIW S2 12.97FACHS3 13.87

which mainly includes the P or S wave arrival picks/time for each station after a certain time for each event.

I read this documentation about how to create a dataset matching with SeisBench requirements:
https://colab.research.google.com/github/seisbench/seisbench/blob/main/examples/03b_creating_a_dataset.ipynb

my problem is that my catalog format is not like ETHZ :-) and it is not on the web. It is simply a txt file in my local device. 

Any idea/help would be appreciated guiding how to solve the issue in such case. I hope solving this issue would be in the interest of the SeisBench developers/team. 

Best regards,
Koushesh

**Comment by yetinam** [comment]
Hey @Koushesh,

thanks for your interest in SeisBench. In general, the conversion process is similar when starting from a catalog in VELEST format. The general steps will be:

- load catalog (you'll probably need to write your own parser or see if there is one available. Maybe obspy can do it?)
- iterate over the traces and:
* write metadata into a dict with column names as used in seisbench
* load and cut the waveforms (for example through fdsn or from your disk)
* pass the metadata entry and the fitting waveform to `writer.add_trace`

Be sure to use the writer with a context manager, i.e., as `with sbd.WaveformDataWriter(...) as writer:`.

There are a few convenience functions implemented in SeisBench. You can find them [here](https://seisbench.readthedocs.io/en/stable/pages/documentation/util.html#module-seisbench.util.trace_ops).

I hope this helps you. Let me know if you have further questions or close the issue if your question has been addressed.

PS: If you would be interested in including your dataset in SeisBench once its finished, we'd be happy to assist in this process.

**Comment by Koushesh** [comment]
Hi @yetinam,

I am wondering if we could have a short talk in one of the zoom/Microsoft Teams/WhatsApp/gmail/telegram/linkedIn platforms. 

We (my supervisor and I) are also interested in including our dataset in SeisBench. 

For setting a probable appointment: I live in Germany and I will be available whole this week till Friday evening.

**Comment by yetinam** [comment]
Hi @Koushesh,

Sure, I'd be happy to have a meeting. However, I'll only be available early next year. For scheduling, please drop me a mail. Just google for the address.
