### ISSUE TITLE
Generate appropriate version number for main branch

### ISSUE THREAD

**Issue by yetinam** [seisbench/seisbench#159]
The way we publish releases, the main branch develops to a stale version number. This can lead to confusion (see #150). To avoid this, version numbers on main should be generated automatically and have some tag associated to them to indicate they are on main.

**Comment by miili** [comment]
I can pitch a PR. Let me know if I should go ahead. Same for #162.

**Comment by yetinam** [comment]
Hi @miili !

Sure, a PR would be very welcome. Probably a joint PR with #162 makes the most sense. It would be good if the PR is consistent with the [CI for publishing versions](https://github.com/seisbench/seisbench/blob/main/.github/workflows/publish-to-pypi.yml). It triggers on any version tag pushed, so I think that should be a rather easy task.
