### ISSUE TITLE
A bug for merging the PhaseNet (not PhaseNetLight) model outputs of continuous data: the sum of 'NPS' outputs exceeds 1 for overlapped waveform segments

### ISSUE THREAD

**Issue by JUNZHU-SEIS** [seisbench/seisbench#160]
An example code snippet of mine is below
```python
		res = model.annotate(st)
		output = np.array([x.data for x in res])
		ps = np.sum(output[1:], axis=0)
		print(ps, ps.max(), np.sum(output, axis=0).max())
```
I got
```bash
[0.00075611 0.00060828 0.00056476 ... 0.00126267 0.00092494 0.00092069] 1.0067469 1.9080054
```
Note this is for the case of default overlap (250), when I change overlap to 1500 as below
```python
		res = model.annotate(st, overlap=1500)
```
I got
```bash
[0.00075611 0.00060828 0.00056476 ... 0.00126293 0.00092514 0.00092065] 1.0727332 1.8698903
```
As the model detects P/S based on P/S output amplitude, respectively, I wonder whether this bug might cause false P/S picks, especially when both P and S amplitudes exceed corresponding thresholds. I guess this bug might lead to cyclic false P and S picks (repeated with a period of **3001-overlap**) which are very close to each other and within the overlapped waveform segments.

Tips: This bug might be due to missing division by the number of overlapped times (e.g., 1 for non-overlapped segments; 2 for segments overlapped two times) after merging model outputs of 30-s waveform segments.

**Comment by yetinam** [comment]
Hi @JUNZHU-SEIS ,

thanks for the report. To allow me to reproduce the issue, can you give a little more detail? Which version of SeisBench are you using and which model? In addition, can you provide me an example waveform, where this issue occurs?
I'm not yet sure, but I suspect the issue is related to the changes in #99.

**Comment by JUNZHU-SEIS** [comment]
Hey @yetinam ,
Thanks for your reply.
I use the PhaseNet (you just updated) model from SeisBench-phasenet-fix branch.
An example waveform (.mseed) and the model (.pt) I trained are both attached.
I also provide a test script for raw model.

As for #99, I suggest using average-stack as the only choice for PhaseNet model because max-stack will break the rule of "NPS should sum to 1". This rule is adopted by PhaseNet not by EQTransformer.

**Comment by yetinam** [comment]
Thanks for the quick reply. I think the attachments are missing though. And yes, probably changing the default is a good choice.

**Comment by JUNZHU-SEIS** [comment]
Sorry! The test waveform and scripts are available now!

**Comment by yetinam** [comment]
Perfect! I now changed the stacking strategy accordingly. Thanks again for spotting and reporting the issue.
