### ISSUE TITLE
How seismbech deal with datasets that have different data sampling rates 

### ISSUE THREAD

**Issue by speedshi** [seisbench/seisbench#165]
Dear SeisBench developers,

Thanks for developing this fantastic software for the community! 
I have a seismic dataset collected by different types of instruments. Therefore, the seismic data have different sampling rates, e.g. 50 Hz, 100 Hz, 200 Hz, and 400 Hz. I wonder how SeisBench processes such heterogeneous datasets internally in terms of phase picking. And in general, what's the best practice for dealing with this kind of data using SeisBench?

Thanks

**Comment by yetinam** [comment]
Hi @speedshi,

thanks for your interest! The answer depends a bit on what you're looking at:
- For picking, i.e., the `annotate`/`classify` functions, each set of model weights has a sampling rate. You can check its value in the `model.sampling_rate` variable. All streams passed to the model will be resampled to this sampling rate before applying the actual deep learning model.
- For training, a dataset is usually loaded with a certain sampling rate. If not and if it has mixed sampling rates, a warning will be issued. All waveforms will than automatically be resampled to this sampling rate when they are queried, for example in the training.

I hope this answers your question. If not, feel free to reopen the issue.

**Comment by speedshi** [comment]
Hi @yetinam ,

Thanks a lot for your explanation. That's very helpful.
For picking, is it feasible to modify the default sampling rate of the pre-trained models in SeisBench (e.g. by passing input parameters)?

**Comment by yetinam** [comment]
Sure! You can just overwrite `model.sampling_rate` after loading the model. Please note that this will apply the model at a sampling rate it was not trained for. In general, this seems to work quite well (within reasonable bounds) but a model trained on the correct sampling rate in the first place might still be better.

**Comment by speedshi** [comment]
Thank a lot for your help!
I am not sure if I understand the internal process correctly. For example, the original EQT model has a sampling rate of 100 Hz and needs 6001 samples (1 minute long). If I change EQT's sampling rate to 200 Hz, the input data will be resampled to 200 Hz (up-sampling or down-sampling); and in the meanwhile, the model still needs 6001 input samples, but at this time the applied window length will be 30 seconds. Is this correct?

**Comment by speedshi** [comment]
Many thanks! Now I understand the process much better.
