### ISSUE TITLE
Access dataset training data

### ISSUE THREAD

**Issue by MarcoEsposito890** [seisbench/seisbench#166]
Hello,

is it possible to access the dataset that was used to train a pre-trained model?

**Comment by yetinam** [comment]
Hi @MarcoEsposito890,
yes, all training datasets are available in `seisbench.data`. For any easy introduction check the tutorial on dataset basics or have a look at [the documentation](https://seisbench.readthedocs.io/en/stable/pages/benchmark_datasets.html).

**Comment by MarcoEsposito890** [comment]
> Hi @MarcoEsposito890,
> yes, all training datasets are available in `seisbench.data`. For any easy introduction check the tutorial on dataset basics or have a look at [the documentation](https://seisbench.readthedocs.io/en/stable/pages/benchmark_datasets.html).

Hello, thank you! So I should refer to the 'split' column of the dataset metadata for information on the train/test datasets you used to train each model?

Side question: when I load a model pre-trained using INSTANCE, should I consider it was trained using the InstanceCounts, InstanceCountsCombined or InstanceGM datasets?

My perplexity stems from the fact the output of the weights_docstring() method of the pre-trained model only tells me it was trained using INSTANCE without further details.

**Comment by yetinam** [comment]
Yes, the 'split' column provides information on the split used. Note that you can access the different parts of the dataset directly using the `train()/dev()/test()` functions.

For INSTANCE, I admit that is not too clearly documented. It's the InstanceCountsCombined dataset.

**Comment by MarcoEsposito890** [comment]
> Yes, the 'split' column provides information on the split used. Note that you can access the different parts of the dataset directly using the `train()/dev()/test()` functions.
> 
> For INSTANCE, I admit that is not too clearly documented. It's the InstanceCountsCombined dataset.

Thank you very much!

**Comment by MarcoEsposito890** [comment]
> Yes, the 'split' column provides information on the split used. Note that you can access the different parts of the dataset directly using the `train()/dev()/test()` functions.
> 
> For INSTANCE, I admit that is not too clearly documented. It's the InstanceCountsCombined dataset.

Hi yetinam, am I to assume that the training and testing with Instance was done using the waveforms corresponding to the respective split, taking a window centered around the pick? Or did you use a sliding time window?

Is there an in-depth documentation about how each pre-trained model was created? Am I to take the "Which Picker Fits My Data? A Quantitative Evaluation of Deep Learning Based Seismic Pickers" as reference?

**Comment by MarcoEsposito890** [comment]
> 

Thanks again. Also kudos on the amazing work in both the paper and Seisbench
