### ISSUE TITLE
Suggest using half input length as the default overlap of picking models

### ISSUE THREAD

**Issue by JUNZHU-SEIS** [seisbench/seisbench#167]
I suggest replace 250 with 1500 as the default overlap for PhaseNet models.

An open question is whether there exist an optimal overlap for phase-picking models.
Simiiar to PhaseNet practice, a half input length (1500 for PhaseNet, [see here for detail](https://github.com/AI4EPS/PhaseNet/blob/87bf71a17f36ce9af0782ea7f4f09d86adfafef4/phasenet/data_reader.py#L69])) seems a better option than 250 (the default overlap for current seisbench). Two reasons are listed below.
1. An overlap of 1500 allows the model to access any waveform segment twice (except the first/last 1500 data points). If 0<overlap<1500, however, overlapped segments will be predicted twice while the non-overlapped segments once. As we can NOT ensure the translative invariability across different parts of input data, equal times for processing (including predicting and stacking) any segments seems a more fair and less biased choice.
2. An overlap of 1500 is the least overlap achieving unbiased prediction and saving runtime.

A detailed comparison of model responses with different overlap and starting point are shown as follows.
![overlap](https://raw.githubusercontent.com/JUNZHU-SEIS/images/main/overlap.gif)
![overlap](https://raw.githubusercontent.com/JUNZHU-SEIS/images/main/overlap250slide.gif)
![overlap](https://raw.githubusercontent.com/JUNZHU-SEIS/images/main/overlap1500slide.gif)
![overlap](https://raw.githubusercontent.com/JUNZHU-SEIS/images/main/overlap3000slide.gif)
Notice that the second P/S arrivals sometimes are missing in the test overlap of 250.

**Comment by yetinam** [comment]
Hi @JUNZHU-SEIS,

thanks for the suggestion and the very illustrative figures too. I agree, increasing the overlap to 1500 should improve the pick consistency considerably at an acceptable performance hit. I will wait with implementing the change until #158 is merged to avoid confusing. I've added this issue to the v0.3 milestone to keep track of this change.
