### ISSUE TITLE
Is there a reason why model.annotate isn't working on my data?

### ISSUE THREAD

**Issue by zxleong** [seisbench/seisbench#169]
The model.annotate works fine when I load waveform streams as demonstrated in the tutorial. However, when I load my own waveform stream, the model.annotate returns 

> 0 Trace(s) in Stream:

I have double check my data and it has:

> 3 Trace(s) in Stream:

For some reason, the annonate function isn't working as intended. Any ideas why this is happening? 

Any help would be greatly appreciated!

**Comment by yetinam** [comment]
Solved through mail. Underlying issue was the capitalization of the components, i.e., SeisBench expects component identifiers to be capitalized.
