### ISSUE TITLE
Dead Kernel when evaluating a model

### ISSUE THREAD

**Issue by MarcoEsposito890** [seisbench/seisbench#170]
Hello,

I'm following the steps used in the training phase_net to evaluate/make predictions from a model but using a pre-trained model instead of training a baseline model.

I have followed these steps:

1.  created a control dataset with end and star samples for each waveform
2. used a Steered generator to obtain windows of 3000 samples length (input of PhaseNet)
3. added the normalize, dtype and probabilistic labeler augmentations to the Generator (same as in the example)
4. created a DataLoader with the generator
5. downloaded a pretrained model (model pretrained on instance, dataset is instance)
6. passed a batch to the model

and at this point the Kernel dies. I'm running everything locally on Jupiter Notebook, but I have the same issue if I run a script using Spyder. I'm on a MacBook Pro with Apple M1 Max..

```
generator = sbg.SteeredGenerator(test, control) #control is a data frame with the start and end samples


# Metadata fields containing the labels (P and S wave picks) 

phase_dict = {
    "trace_P_arrival_sample": "P",
    "trace_S_arrival_sample": "S"
}

augmentations = [
            sbg.SteeredWindow(windowlen=3001, strategy="pad"), #pad window to 3000
            sbg.ChangeDtype(np.float32),
            sbg.Normalize(demean_axis=-1, amp_norm_axis=-1, amp_norm_type="peak"),
            sbg.ProbabilisticLabeller(label_columns = phase_dict, sigma=30, dim=0)
        ]

generator.add_augmentations(augmentations)

model = sbm.PhaseNet.from_pretrained('instance')
model

batch_size = 256
num_workers = 1 

test_loader = DataLoader(generator, batch_size=batch_size, shuffle=False, num_workers=num_workers, worker_init_fn=worker_seeding)

batch = next(iter(dev_loader))

with torch.no_grad():
        pred = model(batch["X"].to(model.device))
        print(pred)
```

Everything works until the last prediction step, at which point my kernel dies.

**EDIT:** 

I have tried increasing the number of workers, and also using only a vector from a batch (so passing a 2D vector to the model) in which case I get this error

RuntimeError: running_mean should contain 3001 elements not 8

**Comment by MarcoEsposito890** [comment]
I have tried (locally on Jupiter Notebook) using the model with random weights

model = sbm.PhaseNet(phases="PSN")

but my kernel dies whenever I try to make a prediction

**Comment by MarcoEsposito890** [comment]
I have tried replicating the example without using a pre-trained model and launching the script by terminal.

I attach the script and the output below.

`#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb  2 10:00:38 2023

@author: marco
"""

import seisbench.data as sbd
import seisbench.generate as sbg
import seisbench.models as sbm
from seisbench.util import worker_seeding

import numpy as np
import matplotlib.pyplot as plt
import torch
from torch.utils.data import DataLoader
from obspy.clients.fdsn import Client
from obspy import UTCDateTime



if __name__ == '__main__':
    
    
    model = sbm.PhaseNet(phases='PNS')
    print(model)

    data = sbd.ETHZ(sampling_rate=100)
    train, dev, test = data.train_dev_test()

    phase_dict = {
        "trace_p_arrival_sample": "P",
        "trace_pP_arrival_sample": "P",
        "trace_P_arrival_sample": "P",
        "trace_P1_arrival_sample": "P",
        "trace_Pg_arrival_sample": "P",
        "trace_Pn_arrival_sample": "P",
        "trace_PmP_arrival_sample": "P",
        "trace_pwP_arrival_sample": "P",
        "trace_pwPm_arrival_sample": "P",
        "trace_s_arrival_sample": "S",
        "trace_S_arrival_sample": "S",
        "trace_S1_arrival_sample": "S",
        "trace_Sg_arrival_sample": "S",
        "trace_SmS_arrival_sample": "S",
        "trace_Sn_arrival_sample": "S",
    }


    train_generator = sbg.GenericGenerator(train)
    dev_generator = sbg.GenericGenerator(dev)

    augmentations = [
        sbg.WindowAroundSample(list(phase_dict.keys()), samples_before=3000, windowlen=6000, selection="random", strategy="variable"),
        sbg.RandomWindow(windowlen=3001, strategy="pad"),
        sbg.Normalize(demean_axis=-1, amp_norm_axis=-1, amp_norm_type="peak"),
        sbg.ChangeDtype(np.float32),
        sbg.ProbabilisticLabeller(label_columns=phase_dict, sigma=30, dim=0)
    ]

    train_generator.add_augmentations(augmentations)
    dev_generator.add_augmentations(augmentations) ## riprova e vedi se il batch d'uscita è lo stesso che hai sul tuo notebook

    
    batch_size = 1
    num_workers = 1  # The number of threads used for loading data

    train_loader = DataLoader(train_generator, batch_size=batch_size, shuffle=True, num_workers=num_workers, worker_init_fn=worker_seeding)
    dev_loader = DataLoader(dev_generator, batch_size=batch_size, shuffle=False, num_workers=num_workers, worker_init_fn=worker_seeding)

    print(next(iter(dev_loader)))

    with torch.no_grad():
            pred = model(next(iter(dev_loader))["X"])
            print(pred)`

`Component order:	ZNE
SeisBench model		PhaseNet

PhaseNet(
  (inc): Conv1d(3, 8, kernel_size=(1,), stride=(1,))
  (in_bn): BatchNorm1d(8, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv1): Conv1dSame(
    (conv): Conv1d(8, 11, kernel_size=(7,), stride=(4,), padding=(3,))
  )
  (bnd1): BatchNorm1d(11, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv2): Conv1dSame(
    (conv): Conv1d(11, 16, kernel_size=(7,), stride=(4,), padding=(3,))
  )
  (bnd2): BatchNorm1d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv3): Conv1dSame(
    (conv): Conv1d(16, 22, kernel_size=(7,), stride=(4,), padding=(3,))
  )
  (bnd3): BatchNorm1d(22, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv4): Conv1dSame(
    (conv): Conv1d(22, 32, kernel_size=(7,), stride=(4,), padding=(3,))
  )
  (bnd4): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (up1): ConvTranspose1d(32, 22, kernel_size=(7,), stride=(4,), padding=(2,))
  (bnu1): BatchNorm1d(22, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (up2): ConvTranspose1d(44, 16, kernel_size=(7,), stride=(4,), padding=(2,), output_padding=(1,))
  (bnu2): BatchNorm1d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (up3): ConvTranspose1d(32, 11, kernel_size=(7,), stride=(4,), padding=(2,))
  (bnu3): BatchNorm1d(11, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (up4): ConvTranspose1d(22, 8, kernel_size=(7,), stride=(4,), padding=(3,))
  (bnu4): BatchNorm1d(8, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (out): ConvTranspose1d(16, 3, kernel_size=(1,), stride=(1,))
  (softmax): Softmax(dim=1)
)
2023-02-02 13:41:16,268 | seisbench | WARNING | Check available storage and memory before downloading and general use of ETHZ dataset. Dataset size: waveforms.hdf5 ~22Gb, metadata.csv ~13Mb
{'X': tensor([[[-0.0492, -0.0215,  0.0539,  ...,  0.3237,  0.3319,  0.3384],
         [ 0.0014,  0.0013,  0.0039,  ..., -0.0348, -0.0394, -0.0422],
         [-0.1272, -0.0910, -0.0568,  ..., -0.0137, -0.0293, -0.0402]]]), 'y': tensor([[[ 1.9155e-29,  1.3048e-29,  8.8788e-30,  ...,  0.0000e+00,
           0.0000e+00,  0.0000e+00],
         [8.5579e-154, 2.0724e-153, 5.0131e-153,  ...,  0.0000e+00,
           0.0000e+00,  0.0000e+00],
         [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  ...,  1.0000e+00,
           1.0000e+00,  1.0000e+00]]], dtype=torch.float64)}
[W NNPACK.cpp:53] Could not initialize NNPACK! Reason: Unsupported hardware.
zsh: segmentation fault  python3 testETZ.py`

**Comment by yetinam** [comment]
Hi @MarcoEsposito890 ,

this seems to be a pytorch issue to me, maybe related to this: https://discuss.pytorch.org/t/bug-w-nnpack-cpp-80-could-not-initialize-nnpack-reason-unsupported-hardware/107518
As a quick check, you could try just running the model on a random tensor and see if it still crashes.
```python
model = sbm.PhaseNet()
x = torch.rand(2, 3, 3001)
model(x)
```
I'd suspect that this will fail too. This seems to be related to the M1 chip. If that's the case, I'm afraid I won't be able to help with the issue as I don't have access to this chip and would refer you to the pytorch support channels.

**Comment by MarcoEsposito890** [comment]
> Hi @MarcoEsposito890 ,
> 
> this seems to be a pytorch issue to me, maybe related to this: https://discuss.pytorch.org/t/bug-w-nnpack-cpp-80-could-not-initialize-nnpack-reason-unsupported-hardware/107518 As a quick check, you could try just running the model on a random tensor and see if it still crashes.
> 
> ```python
> model = sbm.PhaseNet()
> x = torch.rand(2, 3, 3001)
> model(x)
> ```
> 
> I'd suspect that this will fail too. This seems to be related to the M1 chip. Could you confirm this? If that's the case, I'm afraid I won't be able to help with the issue as I don't have access to this chip and would refer you to the pytorch support channels.

Hello, thanks for the link. I did some further testing and running the code on Colab does remove the dead kernel issue, so I think you are right and it depends on the M1 chip. I will try asking the PyTorch support.
