### ISSUE TITLE
Question about component_order?

### ISSUE THREAD

**Issue by zhong-yy** [seisbench/seisbench#172]
Hi, I have a question about `trace_component_order` in metadata.csv and `data_format` in hdf5. Do they have to be a permutation of `Z, N, E`? 
What if a dataset contains `Z, N, E, 1, 2, 3` components? Do I need to rotate the components to ZNE first?

**Comment by yetinam** [comment]
Hi @zhong-yy ,
the `trace_component_order` can be specified in the metadata.csv separately for each trace. All characters can be used. However, the waveforms returned by `get_waveforms` and similar will be in the order specified in the `data.component_order` attribute. If you'd like to use mixed orders, my recommendation would be to either:
- rotate the data before conversion
- or load the dataset and overwrite the component order, e.g., N to 1 and E to 2. However, this does not rotate the trace, so if orientation matters, this approach is not viable.

Let me know if this solves your question.

**Comment by zhong-yy** [comment]
Hi @yetinam, thank you for your quick reply. It solves my question. The first approach seems more reasonable. For the second approach, do you mean changing the `trace_component_order` column of the `data.metadata` DataFrame directly?

**Comment by yetinam** [comment]
Yes, that's exactly the second approach. It's without question quick and dirty and if you have the information, I'd stick to the first option.

**Comment by zhong-yy** [comment]
Thanks again for your answer
