### ISSUE TITLE
Invalid URL. Request returned status code 404 with DPP list_pretrained method

### ISSUE THREAD

**Issue by MarcoEsposito890** [seisbench/seisbench#173]
Hello,

I keep getting an Invalid URL. Request returned status code 404** error when trying to get the list of pretrained models for DPP. This does not happen for other models.

I need to download the instance pre-trained version of the Deep Phase Picker.

**Comment by yetinam** [comment]
Hi @MarcoEsposito890 ,

I had a look at it and indeed the folders were named incorrectly on our servers. I've now fixed the access to `DPPDetector` weights. For `DPPPicker`, the weights are available [here](https://dcache-demo.desy.de:2443/Helmholtz/HelmholtzAI/SeisBench/models/dpppickerp/) and [here](https://dcache-demo.desy.de:2443/Helmholtz/HelmholtzAI/SeisBench/models/dpppickers/). However, I would very much advise not to use them, as the performance is clearly inferior to other models. The same holds for DPPDetector.

**Comment by MarcoEsposito890** [comment]
> Hi @MarcoEsposito890 ,
> 
> I had a look at it and indeed the folders were named incorrectly on our servers. I've now fixed the access to `DPPDetector` weights. For `DPPPicker`, the weights are available [here](https://dcache-demo.desy.de:2443/Helmholtz/HelmholtzAI/SeisBench/models/dpppickerp/) and [here](https://dcache-demo.desy.de:2443/Helmholtz/HelmholtzAI/SeisBench/models/dpppickers/). However, I would very much advise not to use them, as the performance is clearly inferior to other models. The same holds for DPPDetector.

Thank you! Is it possible import the model from the .pt and .json file via seisbench.models module? Or do I need to redefine the model with pytorch?

**Comment by yetinam** [comment]
You only really need the .pt file. Just create the model and then load the weights as shown [here](https://pytorch.org/tutorials/beginner/saving_loading_models.html#saving-loading-model-for-inference).
