### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by zhong-yy** [seisbench/seisbench#179]
Hi, I notice the values in `trace_p_arrival_sample` column in the STEAD dataset are not exact integers. Why? If I understand correctly, it represents the index of the p arrival in the array of waveform samples.

**Comment by yetinam** [comment]
Hi @zhong-yy,
these values were taken verbatim from the original STEAD publication, so you'll have to direct your question there. However, as this occurs as well in datasets we compiled ourselves, here's my suspicion. In catalogs the picks are provided as times, not samples. When converting these times into samples, they might not end up at a full sample. Clearly, one could round to the nearest sample before writing the dataset, but I think there is not really a need for this and maybe the additional "precision" will actually be useful.
