### ISSUE TITLE
Labelling Sliding Windows

### ISSUE THREAD

**Issue by MarcoEsposito890** [seisbench/seisbench#182]
Hello,

is it possible to add a ProbabilisticPointLabeler (or similars) to a sliding window? I get this error whenever I try

More than one label provided. For multi_class problems, only one label can be provided per input.

is it possible to assign one label per window?

**Comment by yetinam** [comment]
Hi @MarcoEsposito890 ,
yes, that should be possible. Try setting the `dim` parameter when creating your labeller. I think it should be `dim=-2` but I'm not absolutely sure right now.

**Comment by MarcoEsposito890** [comment]
> Hi @MarcoEsposito890 , yes, that should be possible. Try setting the `dim` parameter when creating your labeller. I think it should be `dim=-2` but I'm not absolutely sure right now.

Hello. I was able to do it by setting 'dim=-1'. Thanks for the reply.

I am trying to obtain a characteristic function of sorts for GPD labels and GPD outputs, but I'm not sure if the way I do the labelling is wrong. I have taken inspiration from the code in the eval.py script in the benchmarking repository, but the results I obtain with GPD seem to be quite bad. I use the GPD outputs and the labels on each sliding window to create the char functions for both the output and the "ground truth".

For example, on a small batch I obtain the following results. Each red line separates a model output/label couple. While some picks are good, there are many false detections when the trace had no picks (first two couples), or another pick is detected after the main one.
<img width="880" alt="image" src="https://user-images.githubusercontent.com/48209182/223766287-8b92e1a9-298b-417f-b83b-b4ccad204c0b.png">

I'm unsure if the labelling could be an issue, or if it's to be expected of GPD.

If this side question is off topic I can move it to the benchmarking repository. Sorry in advance for the long message.

**Comment by yetinam** [comment]
Hi! Glad the labelling now works. To answer your question on GPD, These curves unfortunately seem realistic to me. From experience, GPD produced pretty high confidence even where there is no event. Still, our benchmark showed that a significantly high cut-off still often solves this. In any case, I'd recommend to check the waveforms to see if there might not actually be another arrival.

In general, I'd discourage the use of GPD because it is a lot slower than PhaseNet or EQTransformer. Is there any particular reason you want to use GPD?

**Comment by MarcoEsposito890** [comment]
> Hi! Glad the labelling now works. To answer your question on GPD, These curves unfortunately seem realistic to me. From experience, GPD produced pretty high confidence even where there is no event. Still, our benchmark showed that a significantly high cut-off still often solves this. In any case, I'd recommend to check the waveforms to see if there might not actually be another arrival.
> 
> In general, I'd discourage the use of GPD because it is a lot slower than PhaseNet or EQTransformer. Is there any particular reason you want to use GPD?

Hello! I'm evaluating an embedded implementation of GPD. I would like to have a sort-of characteristic function over the sliding windows to compute some kind of loss function for the predictions, hence the use of the labels on each sliding window.

From your benchmarking it seemed to me that GPD and PhaseNet performed similarly, but maybe you used a high threshold on the GPD pickings? For now I'm just using argmax on the raw char functions to find residuals but maybe a threshold is needed first

**Comment by yetinam** [comment]
Indeed, they perform similar but the thresholds are different. However, PhaseNet is orders of magnitude faster than GPD because it annotates the window at once and not piece-wise.

I'll close this issue for now. Feel free to reopen if there are further questions.

**Comment by MarcoEsposito890** [comment]
> 

Hi yetinam. From the models.py, eval.py and collect_results.py scripts in the benchmark repository I do not see any threshold applied to the prediction of the onset points (which is just the argmax of the probability function). Is a threshold applied in post-processing?

**Comment by yetinam** [comment]
Seems like there has been a slight misunderstanding. Indeed, our evaluation does not use any thresholding. We look at certain windows but do not apply threshold. What I meant is that when annotating long waveforms and extracting picks, we define everything as a pick that is above a certain threshold. This is necessary as the number of picks in the long waveform is not known a priori. This threshold should be chosen pretty high for GPD.

**Comment by MarcoEsposito890** [comment]
> Seems like there has been a slight misunderstanding. Indeed, our evaluation does not use any thresholding. We look at certain windows but do not apply threshold. What I meant is that when annotating long waveforms and extracting picks, we define everything as a pick that is above a certain threshold. This is necessary as the number of picks in the long waveform is not known a priori. This threshold should be chosen pretty high for GPD.

Hi yetinam, sorry if I reopen this fairly old issue. I was using PhaseNet on continuous data and noticed that with lower thresholds (the one that maximizes the F1 Score) I detect all events including high magnitude events. I have then heightened the threshold and noticed that this way I can "filter out" the lower magnitude events. While seemingly an intuitive result, I was wondering if this behavior is just a case by case thing, if it depends on the fact I'm not analyzing standalone samples but a stream, or if it can be justified by the network architecture? Or maybe a mix of all ^_^
 
My doubt stems from the fact I'm using normalized windows as input to PNet, likely meaning that the event intensity information might not be directly influencing the prediction result or the amplitude of the probability function?

**Comment by yetinam** [comment]
Hi! I'm not aware if anyone has formally observed this, but it is indeed intuitive. While the normalization will destroy the amplitude information, a critical information stays intact: the signal-to-noise ratio (SNR). Multiple studies have shown that a high SNR corresponds to better predictions and higher confidence. So if you use a higher threshold, you'll tend towards events with better SNR, i.e., usually larger events.

**Comment by MarcoEsposito890** [comment]
> Hi! I'm not aware if anyone has formally observed this, but it is indeed intuitive. While the normalization will destroy the amplitude information, a critical information stays intact: the signal-to-noise ratio (SNR). Multiple studies have shown that a high SNR corresponds to better predictions and higher confidence. So if you use a higher threshold, you'll tend towards events with better SNR, i.e., usually larger events.

Thanks for the answer! I reread the original PNet paper and EQTransformer papers and they indeed draw a correlation between high SNR and better detection, but I did not make that connection.

I made a quick scatter plot with STEAD and a version of Pnet I modified, and it shows that with higher snrs the detection score tends to go up so it checks out.
