### ISSUE TITLE
issue when resampling input stream

### ISSUE THREAD

**Issue by speedshi** [seisbench/seisbench#184]
Dear SeisBench developers:

The resampling process of stream data in "base.py" is designed as follows:
[RESAMPLE](https://github.com/seisbench/seisbench/blob/51fd617c6af7fb37d699193ed61e73d254dd0dcd/seisbench/models/base.py#L2089)
_if trace.stats.sampling_rate % sampling_rate == 0:
                trace.filter("lowpass", freq=sampling_rate * 0.5, zerophase=True)
                trace.decimate(
                    int(trace.stats.sampling_rate / sampling_rate), no_filter=True
                )
            else:
                # This exception handling is required because very short traces in obspy can cause a crash during resampling.
                # For details see: https://github.com/obspy/obspy/pull/2885
                # TODO: Remove the try except block and bump obspy version requirement to a version without this issue.
                try:
                    # window="hann" is required because of https://github.com/obspy/obspy/issues/3116
                    # Should be fixed in obspy>=1.3.1
                    trace.resample(sampling_rate, no_filter=True, window="hann")
                except ZeroDivisionError:
                    del_list.append(i)_

I feel: this is fine for upsampling and also fine for downsampling to an integer fraction of the original sampling rate.
However, if we want to resample from 400 Hz to 300 Hz, lowpass filtering (used for removing aliasing when downsampling) is missing. (Am I right on this?)

If this is the case, I suggest first applying a lowpass filtering whenever downsampling is needed.

Best regards,
Peidong

**Comment by yetinam** [comment]
Hi Peidong,

thanks for the issue. I though about it, and I think when resampling in Fourier domain, there is no need for the lowpass. The lowpass saves against alias artifacts. However, when downsampling in frequency domain, we anyhow only keep the lower frequencies, i.e., it implicitly lowpass-filters the data. The filter is naturally zero-phase. Did you experience any issue with alias artifacts?

**Comment by speedshi** [comment]
Hi Jannes,

Many thanks for your response. I double-checked the downsampling effect with example data. Indeed, when downsampling using the "resample" method in ObsPy, lowpass filtering seems not necessary. No aliasing is observed in my example. Directly using resample shows almost the same effect as first lowpass filtering and then resample the data; the only subtle differences exist in a few very beginning and ending points.

Thanks,
Peidong

**Comment by yetinam** [comment]
Okay, thanks for checking. Closing this now as it seems to be now problem. But I also used the chance to do a little cleanup in [eb7e5a5](https://github.com/seisbench/seisbench/commit/eb7e5a5ade27fbf229aa8f83f93341bb3b30e44b).
