### ISSUE TITLE
Question: how to combine two datasets quickly?

### ISSUE THREAD

**Issue by zhong-yy** [seisbench/seisbench#189]
Hi, are there any functions to combine two datasets into one, or split one dataset into two?

For the first question, if I have two separately downloaded datasets with the same metadata columns, is it a valid chunking to put the two datasets into one folder?

**Comment by yetinam** [comment]
The easiest option is simply to load both datasets separately and just add with `dataset1 + dataset2`. For a more permanent option, you can indeed use chunking. Have a look at the [chunking documentation](https://seisbench.readthedocs.io/en/stable/pages/data_format.html#chunking-datasets) for details. For splitting a dataset, you need to use the `filter` function.

**Comment by zhong-yy** [comment]
Thank you very much! For splitting, can I save the filtered dataset directly?

**Comment by zhong-yy** [comment]
Hi @yetinam, after adding two datasets with dataset1 + dataset2. There are repeated indexes. Does it matter?

**Comment by yetinam** [comment]
HI @zhong-yy ,

there is currently no direct way to save a (filtered or merged) dataset. The best choice is to iterate over the dataset and pass the samples to a `WaveformDataWriter`. Not that this can get somewhat tedious if the dataset should have mixed component order or sampling rate and you'd like to preserve this.

Regarding the duplicate indices, I think this should not cause any issues but please let me know if you experience problems.

**Comment by zhong-yy** [comment]
Thanks again for answering my question!

**Comment by zhong-yy** [comment]
> HI @zhong-yy ,
> 
> there is currently no direct way to save a (filtered or merged) dataset. The best choice is to iterate over the dataset and pass the samples to a `WaveformDataWriter`. Not that this can get somewhat tedious if the dataset should have mixed component order or sampling rate and you'd like to preserve this.
> 
> Regarding the duplicate indices, I think this should not cause any issues but please let me know if you experience problems.

I think duplicate indices may cause problems when one tries to use index to locate some metadata.
