### ISSUE TITLE
Different input sizes to PhaseNetLight (or PhaseNet)

### ISSUE THREAD

**Issue by MarcoEsposito890** [seisbench/seisbench#190]
Hello,

while I have noticed that BasicPhaseAE model takes any input size to make predictions (even though the output probability does not reflect the input size in some cases), PhaseNetLight gives an exception when trying to pass it input less than 3001 samples long.

The BasicPhaseAE code says that "by default" the input size is 600 samples, while nothing of the sort is said for PhaseNetLight. Is it impossible to pass different input sizes to PhaseNetLight? Is BasicPhaseAE meant to work with different sizes?

I was downloading a model pretrained on ETHZ. Do I need to initialize the model, pass it a different input size (in_samples), and then manually load the weights?

**Comment by yetinam** [comment]
Hi @MarcoEsposito890 ,

thanks for your question. Indeed, it is not possible to pass different input sizes to PhaseNet or PhaseNetLight. In principle, a U-Net should be scalable, but in practices there are two issues: boarder artifacts and padding/stride. In particular, getting the padding right is a bit of a nuisance. That also means that pretrained weights will most likely not work properly if you change the input length.

Out of curiosity, may I ask why you'd like to use a different number of input samples?

**Comment by MarcoEsposito890** [comment]
> Hi @MarcoEsposito890 ,
> 
> thanks for your question. Indeed, it is not possible to pass different input sizes to PhaseNet or PhaseNetLight. In principle, a U-Net should be scalable, but in practices there are two issues: boarder artifacts and padding/stride. In particular, getting the padding right is a bit of a nuisance. That also means that pretrained weights will most likely not work properly if you change the input length.
> 
> Out of curiosity, may I ask why you'd like to use a different number of input samples?

Thanks (again) for the reply. I was trying to do a rough evaluation of a PhaseNetLight with input sizes closer to BasePhaseAE or GPD architectures, but it's not as straightforward as I thought. Seeing it's based on U-Net I believed it would be scalable.

I have also tried the opposite (i.e. passing a longer window to BasePhaseAE to see if the picking residuals get lower with a longer view of the waveform), but while it worked in theory, I got an output size that's not the same as the input (3x3000 samples in input led to 3x3450 samples in output), so I assume the same thing applies also to this other architecture.

**Comment by yetinam** [comment]
Yes, exactly. That's also caused by the padding issue.
