### ISSUE TITLE
Ambiguity in documentation

### ISSUE THREAD

**Issue by imankahbasi** [seisbench/seisbench#192]
Hello,

I observed that the related model's section has parameters that can be defined during model creation.

![Screenshot from 2023-04-24 12-13-18](https://user-images.githubusercontent.com/47061763/233954636-f8d36b68-08dc-4519-962f-9963f5b56759.png)

I attempted to modify these parameters to see if they would impact the model's performance. But they don't change!

![Screenshot from 2023-04-24 12-10-49](https://user-images.githubusercontent.com/47061763/233952803-97e77c71-090f-4006-8db0-f84decb5fbb9.png)

However, it's crucial to have fixed input dimensions when defining a deep learning model. This is because the proportional coefficients for the first hidden layer need to be based on the input dimensions, and once they're established, all inputs must have the same dimensions. Therefore, it seems logical that we cannot change these parameters.
My primary question is, why are these values defined as variables in the input of the model if they're fixed and cannot be changed?

Thank you for your assistance.

**Comment by imankahbasi** [comment]
Thanks, @yetinam 
I understood!
My next question is about the use of `eqt2`.
Does It use only when I want to train a model?

**Comment by yetinam** [comment]
Exactly, the varying input samples can be used when you train a new model. In general, I'd recommend to keep the original number of input samples because that's what the models were originally designed for, so the choice of the number of layers etc is probably adjusted to it.
