### ISSUE TITLE
Possible issue in PickBlue's detections

### ISSUE THREAD

**Issue by alirezaniki** [seisbench/seisbench#195]
Hi, I am adopting the PickBlue picker on some OBS data from its test dataset. Typically, the detected P and S phase arrivals must fall within a detection window, however, I happened to face several accurate S detections outside the reported detection intervals. Here is an example:

picks:
OB.LT13.	2018-09-12T15:11:55.973500Z	S
detections:
OB.LT13.	2018-09-12T**15:11:33.203500Z**	2018-09-12T1**5:11:53.503500Z**
OB.LT13.	2018-09-12T**15:12:05.083500Z**	2018-09-12T**15:12:24.203500Z**

Is it meant to work like this?

**Comment by yetinam** [comment]
Hi @alirezaniki ,
in principle, this can happen. Sometime the model is confident enough on one (or even both phases) but not for detections. In your example, the model did not detect a P wave, which probably also reduced the confidence for the detection curve. For a better understanding, I'd recommend to plot the output of `model.annotate`. Maybe you also could lower your thresholds? Just pass `P_threshold=0.05` / `S_threshold=0.05` / `detection_threshold=0.05` to the `annotate` function as additional arguments.

**Comment by yetinam** [comment]
Closing this now. Feel free to reopen if necessary.
