### ISSUE TITLE
Usage and documentation

### ISSUE THREAD

**Issue by imankahbasi** [seisbench/seisbench#197]
Hi there,

I'm having trouble understanding how to use `detections = model.classify(stream, **kwargs)` since I haven't been able to locate any documentation regarding the required keyword arguments (`kwargs`).

![Screenshot from 2023-05-08 13-25-29](https://user-images.githubusercontent.com/47061763/236798219-33876451-a219-46ac-8420-65abf22d1c7a.png)

Although I found an example of the keyword arguments in the "01b_model_api.ipynb" file on GitHub, it appears to be incomplete, and there might be additional keyword arguments that are not covered in the example.

![Screenshot from 2023-05-08 13-30-51](https://user-images.githubusercontent.com/47061763/236798289-8f94ab08-d5e7-422b-bfd2-1263a4ceb4bd.png)

Could you please provide more information regarding the other keyword arguments required and their default values?
Are these default values different for different models?

**Comment by yetinam** [comment]
Hi @imankahbasi ,
Thanks for reaching out. The optional arguments for each model are documented at the top of the model class in the documentation. See for example the table for PhaseNet [here](https://seisbench.readthedocs.io/en/stable/pages/documentation/models.html#module-seisbench.models.phasenet). The table also lists the default values.

**Comment by imankahbasi** [comment]
Thank you, @yetinam !
I apologize for my inability to find the required information and any inconvenience it may have caused you.
