### ISSUE TITLE
Loading Seisbench DeepDenoiser model

### ISSUE THREAD

**Issue by graalop** [seisbench/seisbench#200]
Hello,

I've been using Seisbench models for quite some time, recently, I can no longer load the models and I'm getting the following message.

![Screenshot 2023-05-14 125524](https://github.com/seisbench/seisbench/assets/100480619/45c80c30-8f5f-4797-a2a8-8ae5a3d6afb7)

**Comment by yetinam** [comment]
Hi @graalop ,
thanks for alerting us of this. I've reached out to our admin to fix the certificate issue. I'll post an update when I hear back.

**Comment by yetinam** [comment]
Things should be back to normal again. Please confirm and reopen the issue if you're still experiencing problems.

**Comment by MarcoEsposito890** [comment]
> 

I was experiencing the same issue when downloading datasets, and now everything is back to normal again (both models and datasets dowload)

**Comment by graalop** [comment]
Thank you, yes it's back to normal
