### ISSUE TITLE
Query Regarding Default Filters, Resampling, and Customization Options in SeisBench Models

### ISSUE THREAD

**Issue by imankahbasi** [seisbench/seisbench#201]
Hello and best regards,

I would like to inquire about the SeisBench models regarding the presence of default filters within the classify and annotate methods. Specifically, I'm interested to know if these methods process the raw data or if any filtering is applied by default.

Additionally, I'm curious about the resampling of data. Is it consistently set to 100 sps (samples per second) for all models? 

Lastly, I would like to inquire whether there are any options available to control and personalize each of the aforementioned aspects.

**Comment by yetinam** [comment]
Hi @imankahbasi ,

thanks for your question. The filter behaviour of the models is specified in their `filter_args` and `filter_kwargs` attributes. Most models do not apply any filtering. You can change the filter behaviour by modifying these attributes. Please be aware that this will add filtering only for the `annotate`/`classify` functions.

For the sampling rate, currently all models use 100 Hz, but SeisBench can also deal with other frequencies. When provided with a stream (again, for `annotate`/`classify`), SeisBench will resample it to the target sampling rate of the model. The target sampling rate can be changed by overwriting the `sampling_rate` attribute of the model. You can change this value but for pretrained models, this is a way of tricking the model. For example, by setting the value to 50, you'd apply a model trained on 100 Hz to 50 Hz data. Surprisingly, this seems to work well rather often.

Hope this answered your questions.

**Comment by yetinam** [comment]
Closing this for now. Feel free to reopen if there are further questions.

**Comment by imankahbasi** [comment]
Thank you (@yetinam ) for your good explanation.
