### ISSUE TITLE
GenericGenerator not iterable "ValueError: axes don't match array"

### ISSUE THREAD

**Issue by mihtm13** [seisbench/seisbench#203]
Hello everyone,
in my code below I started playing around with example from the [https://github.com/seisbench/pick-benchmark/blob/main/analysis.ipynb](https://github.com/seisbench/pick-benchmark/blob/main/analysis.ipynb) repository. 
Sadly i got the Error Message when I put in my own Data: 

```
Exception has occurred: ValueError
axes don't match array
  File "/X/Y/Z/Seisbench/Test/model.py", line 44, in <module>
    sample = test_generator[idx]
ValueError: axes don't match array
```

My Code:

```
# -*- coding: utf-8 -*-

# Built-in / Generic Imports
import time
import os

# Libs
import seisbench
import seisbench.models as sbm
import seisbench.data as sbd
import seisbench.generate as sbg
import matplotlib.pyplot as plt
import numpy as np
import torch


path_proj_dslq = '/X/Y/Z/Seisbench/Test/Dataset_LQ/'

#Models
#model = sbm.GPD.from_pretrained("original")
model = sbm.EQTransformer()
#model = sbm.PhaseNet.from_pretrained("original")


# now the GPU will automatically process the computations of annotate and classify
model.cuda()


# preloading data into cache
data = sbd.WaveformDataset(path_proj_dslq, sampling_rate=125, component_order='ZNE', missing_components='pad')
#data = sbd.WaveformDataset(path_ethz, cache='trace', sampling_rate=100)
#data.preload_waveforms(pbar=True)
print(data)
print(data.metadata)
print(data.data_format)

test_generator = sbg.GenericGenerator(data)

for idx in range(1, len(test_generator), 1):

    loop_start = time.time()

    sample = test_generator[idx]

    x = sample['X']
    y = sample['y']

    fig = plt.figure(figsize=(15, 10))
    axis = fig.subplots(3, 1, sharex=True, gridspec_kw={'hspace': 0, 'height_ratios': (3, 1, 1)})

    with torch.no_grad():
        pred = model(torch.tensor(x.reshape(1, 3, 3001)))
        pred = pred.cpu().numpy()[0]

    axis[0].plot(x.T)
    axis[1].plot(y.T)
    axis[2].plot(pred.T)

    batch = {key: torch.tensor(val).unsqueeze(0) for key, val in sample.items()}
    batch['window_borders'] = torch.tensor([[0, 3000]])

    score_detection, score_p_or_s, p_sample, s_sample = model.predict_step(batch)
    axis[2].axvline(p_sample[0], color='C0')
    axis[2].axvline(s_sample[0], color='C1')

    print('Detection probability: ', score_detection[0].item())
    print('P or S: ', score_p_or_s[0].item())
    print('P Sample', p_sample[0].item())
    print('S Sample', s_sample[0].item())

```
Did anybody had this issue before?

It worked perfectly fine with the ETHZ-Benchmark dataset.

Please excuse formatting as this is my first issue post.

Thanks in advance

**Comment by yetinam** [comment]
Hi @mihtm13 ,

thanks for your question. I'd suspect that the issue arises from the shape of the data arrays in your dataset. To give you a more precise answer, it would be helpful if you could past the full stack trace python outputs with the error.

**Comment by mihtm13** [comment]
Hi @yetinam,
thanks for the reply.

The Output looks like this:
![Screenshot_git_issue#203](https://github.com/seisbench/seisbench/assets/134383604/40a0f4ca-22c3-43fb-b08c-472aaeada048)

**Comment by yetinam** [comment]
Indeed, the shape needs to be 2D. It should be (1, x) though, not (x, 1).

**Comment by yetinam** [comment]
You should check the value for `"trace_component_order"` in the metadata. If you are passing one component data, the value needs to be a single character.

**Comment by mihtm13** [comment]
Indeed, the shape needs to be 2D. It should be (1, x) though, not (x, 1).

Thank you very much. 
After recreating the dataset i got the 2D-shape right, but now the `data.get_waveforms(0)` gets me an index out of bounds error, like below:
![Screenshot_git_issue#203_index out of bounds](https://github.com/seisbench/seisbench/assets/134383604/10d4e416-309e-4346-88e9-e661539898b0)


Now I'll proceed to the method where I pass a (3, X) array of data with the metadata-dict for the channels, as I thinks thats the intended way from the example.
