### ISSUE TITLE
list_pretrained

### ISSUE THREAD

**Issue by graalop** [seisbench/seisbench#209]
Hello,

while running this line of code below, I got the attached error:

import seisbench.models as sbm
sbm.DeepDenoiser.list_pretrained(details=True)

![image](https://github.com/seisbench/seisbench/assets/100480619/a26340ec-f17b-43a9-af86-e945d0ae0bd7)

**Comment by yetinam** [comment]
Hi @graalop ,
this error is caused by a recent change in our remote repository url. Please see the solutions detailed [here](https://github.com/seisbench/seisbench#known-issues).
