### ISSUE TITLE
Extracting data with particular constraints

### ISSUE THREAD

**Issue by TayyabaZainab0807** [seisbench/seisbench#210]
Hello, I am new to this repo and I need some assistance, I want to test eqtransformer on a dataset other than STEAD data. I am just using seisbench to have a test dataset with 1 min window and 100 Hz per sec with metadata that contains p and s arrival.

Can someone guide me, how I can do that?

**Comment by yetinam** [comment]
Hi @TayyabaZainab0807 ,
thanks for your interest in SeisBench. In general, as a starting point I'd recommend the SeisBench tutorial notebook. I'm not sure I fully understand what exactly you want to do. Can you provide more detail on what you are aiming to analyze? Maybe I can give you further pointers then.

**Comment by TayyabaZainab0807** [comment]
I have eqtransformer model that I trained on STEAD dataset (input shape is (6000,3) for a 1min input window), I want to test the same model on a different data with but 1st have the same input dimension and 2nd need a corresponding metadata that contains p and s arrivals.

**Comment by yetinam** [comment]
Hi @TayyabaZainab0807 ,
do you have specific data you want to test on? In this case, have a look at [this tutorial](https://colab.research.google.com/github/seisbench/seisbench/blob/main/examples/03b_creating_a_dataset.ipynb) on how to convert it to SeisBench format or directly use the [annotate/classify API](https://colab.research.google.com/github/seisbench/seisbench/blob/main/examples/01b_model_api.ipynb). If you're looking for a dataset to use, have a look at the [datasets already in SeisBench](https://seisbench.readthedocs.io/en/stable/pages/benchmark_datasets.html).

**Comment by yetinam** [comment]
Closing this issue as inactive. Feel free to reopen if you have further questions.
