### ISSUE TITLE
GaMMa reults plot seismic section shows bad hypocentral distances

### ISSUE THREAD

**Issue by jasonski** [seisbench/seisbench#212]
Hi, I found that the last figure in the GaMMa example has some bug in the Y axis. When using the code, the station order often is quite wrong (so earliest p pick trace does not come first, second not second etc.). Even in your data example the s-p time difference does never! allow a 150km hypocentral distance. The map plot, however, shows reasonable locations. So it is not the event position, but something like station or event coordinate conversion that produce the error.  I did not locate the error. sry.

**Comment by yetinam** [comment]
Hi @jasonski ,

thanks for reporting this. Indeed, the plots look extremely odd (example below). I'll have a look into it.

![image](https://github.com/seisbench/seisbench/assets/14940857/b2b93b0f-ebb2-40ee-9eb5-66eb8a6a046e)

**Comment by yetinam** [comment]
Found the issue. It was an off-by-one error leading to the wrong event being selected. The cross-sections should look much nicer again now.

**Comment by jasonski** [comment]
Yea, looks good to me now.
