### ISSUE TITLE
EQTransformer Preprocessing

### ISSUE THREAD

**Issue by AMindToThink** [seisbench/seisbench#213]
Hi Seisbench,
EQTransformer expects the input data to be demeaned, detrended, bandpass filtered, filled in, and sampled to 100Hz. It seems to me that Seisbench only demeans and resamples for EQTransformer. Do we need to do the rest of the preprocessing ourselves? To do so requires we become familiar with each model which makes it harder to use and compare models. 

Setting model.norm_detrend to True makes the preprocessing detrend the data where it otherwise would not.

**Comment by yetinam** [comment]
Hi,
Thanks for your question. All preprocessing is automatically applied. The filtering is specified separately for each set of trained weights and automatically loaded. Depending on the parameter `strict` missing components are either filled with zeros or the corresponding segments are ignored. Please not that all of these steps are only applied when using the `annotate/classify` interface but not for the direct pytorch interface. I hope this answers your question.
