### ISSUE TITLE
Initialization of the PhaseNet / EQTransformer models

### ISSUE THREAD

**Issue by graalop** [seisbench/seisbench#216]
Hello, I've been testing the models with the different datasets they were trained on and applied them to my dataset. Just yesterday, I started getting this error where PhaseNet model worked fine when using the weights of the "original" dataset, but gives me this error if I choose another dataset. Same for EQTransformer.
![image](https://github.com/seisbench/seisbench/assets/100480619/0a29b63e-a8a4-473e-8360-d728f532b84b)

**Comment by yetinam** [comment]
Hi @graalop ,

thanks for your question. I suspect something yesterday triggered an update of your cached weights. The `norm` parameter was added in v0.3.2. Could you updated your SeisBench to the latest version?

**Comment by graalop** [comment]
Thank you, it works now. I appreciate your help.
