### ISSUE TITLE
EqTransformer datasets

### ISSUE THREAD

**Issue by graalop** [seisbench/seisbench#218]
What distinguishes the sbm.EQTransformer.from_pretrained("original") and sbm.EQTransformer.from_pretrained("stead") methods? Is the original dataset identical to the stead dataset?

**Comment by yetinam** [comment]
Hi @graalop ,

the "original" model is a converted version of the weights from the original Mousavi paper. The "stead" weights are the weights obtained in our 2022 benchmark study (Which picker fits my data?). The models are both trained on STEAD but and should be similar but not identical.
