### ISSUE TITLE
The widths of the gaussian labelling function and the triangular labelling function are not comparable for the same sigma parameter

### ISSUE THREAD

**Issue by zhong-yy** [seisbench/seisbench#235]
This can be illustrated by the following code. With sigma=20, the gaussian label is twice as wide as the triangle label and the box label. Therefore, their effects on the training cannot be compared directly.
```python
import matplotlib.pyplot as plt
import numpy as np
from seisbench.generate.labeling import gaussian_pick,triangle_pick,box_pick

def normalization(y,label_ids):
    phase_ids=[label_ids[lab] for lab in label_ids.keys() if lab!="Noise"]
    y[phase_ids,:] /= np.maximum(
        1, np.nansum(y[phase_ids,:], axis=0, keepdims=True)
    )
    y[label_ids["Noise"],:]=1-np.sum(y[phase_ids,:],0)

fig,axs=plt.subplots(3,1,figsize=(6,9),sharex="all",sharey="all")
plt.subplots_adjust(wspace=0.05,hspace=0.1)
for i,prob_fun in enumerate([gaussian_pick,triangle_pick,box_pick]):
    length=250
    y=np.zeros((3,length))
    sigma=20
    p=50
    s=p+4*sigma

    y[0,:]=prob_fun(onset=p,length=length,sigma=sigma)
    y[1,:]=prob_fun(onset=s,length=length,sigma=sigma)
    
    label_ids={"P":0,"S":1,"Noise":2}

    normalization(y,label_ids) # normalization
    assert np.all(((y>0)|(np.isclose(y,0)))&((y<1)|np.isclose(y,1)))
    assert np.allclose(np.sum(y, axis=0), 1)


    label_names=["P","S","Noise"]
    for k in range(3):
        axs[i].plot(np.arange(y.shape[-1]),y[k],"-",label=label_names[k])
    
    axs[i].axvspan(p-sigma,p+sigma,color="dodgerblue",alpha=0.3,label=r"$[P-\sigma,P+\sigma]$")
    axs[i].axvspan(s-sigma,s+sigma,color="pink",alpha=0.3,label=r"$[S-\sigma,S+\sigma]$")
    axs[i].axvline(p,ls="-",color="blue",label="True P")
    
    axs[i].axvline(s,ls="-",color="red",label="True S")

    p_peak,s_peak=np.argmax(y[:2,:],axis=1)
    axs[i].axvline(p_peak,ls="--",color="blue",label="Peak P")
    axs[i].axvline(s_peak,ls="--",color="red",label="Peak S")
    axs[i].set_ylabel(prob_fun.__name__)
axs[1].legend(loc="center left", bbox_to_anchor=(1.00, 0, 0.2, 1))
plt.show()
```
![image](https://github.com/seisbench/seisbench/assets/38816011/78cb6a3b-ee8d-46cc-8c42-c91f71e7f98a)

Would it be better to give them similar widths for the same sigma?

**Comment by yetinam** [comment]
Hi @zhong-yy ,
thanks for bringing this up. Indeed, that might be a bit confusing. On the other hand, it seems to be the most natural way of using the sigma parameter for all of these functions and changing it now would lead to backwards compatibility issues. How about instead adding a warning to the documentation? We could include your plot with it to visualize the different meaning of sigma.

**Comment by zhong-yy** [comment]
> Hi @zhong-yy , thanks for bringing this up. Indeed, that might be a bit confusing. On the other hand, it seems to be the most natural way of using the sigma parameter for all of these functions and changing it now would lead to backwards compatibility issues. How about instead adding a warning to the documentation? We could include your plot with it to visualize the different meaning of sigma.

Thanks for your reply. That sounds good to me.

**Comment by yetinam** [comment]
Sorry, the issue slipped my mind for a while. I've created a PR now that incorporates your figure in the documentation. I'll merge once the CI has passed. Thanks again for raising this!
