### ISSUE TITLE
Repository at port 2443 or 2880

### ISSUE THREAD

**Issue by pevans-gfz** [seisbench/seisbench#236]
Documentation text in [README.md](/seisbench/seisbench/blob/main/README.md) at "Known issues" refers to the data and model respository being at port 2443 (twice). But the example and link at "try accessing" both point to port 2880. Which one is correct?

**Comment by yetinam** [comment]
Thanks for pointing this out. It's indeed 2880. It used to be 2443 before a change of the server a few months ago. I've fixed it now.
