### ISSUE TITLE
Difficulty accessing DPP model in SeisBench

### ISSUE THREAD

**Issue by imankahbasi** [seisbench/seisbench#237]
Hello
I'm facing a problem with the DPP model in SeisBench.
Unfortunately, I couldn't find any documentation or manual on the website that explains how to access this particular model.
While all the other models in the "Models integrated into SeisBench" list have clickable links to their manuals, the DPP model doesn't.
I'm unable to use the DPP model even though I have SeisBench installed.
Can you show me how to use DPP in SeisBench please?

**Comment by yetinam** [comment]
Hi @imankahbasi ,
The DPP detector weights are available in the class `DPPDetector`. The DPP Picker weights are available in the repository but need to be downloaded by hand. We have not implemented annotate/classify functions for DPP. As DPP performed substantially inferior to the other model, we do not aim to do so. Is there any specific reason why you are interest in using DPP?

**Comment by imankahbasi** [comment]
@yetinam 

I am currently conducting tests on various models for my regional data to evaluate their performance. The DPP model is one of the models included on my review list.
According to the reviews mentioned in your paper (_**Which Picker Fits My Data? A Quantitative Evaluation of Deep Learning Based Seismic Pickers**_), this model demonstrated good performance in detection but had limitations in phase determination.
Hence, I am interested in investigating its impact on my data and compare with the results of your article.

Additionally, I observed that the original weights for the BasicPhaseAE model are not available.
Could you kindly explain the reason behind this?

**Comment by yetinam** [comment]
Hi @imankahbasi ,

Thanks for the explanation. I'm sorry but there won't be capacity on my side to add the annotate/classify functions for DPP. However, if you should decide to implement that, I'd happily accept a PR.

Regarding the original weights for BasicPhaseAE, as far as I remembered they have not been published so they could not be added to SeisBench.
