### ISSUE TITLE
Classify method for the DepthPhaseTEAM model is not implemented correctly

### ISSUE THREAD

**Issue by AliceBlackwell** [seisbench/seisbench#242]
The classify method for the DepthPhaseTEAM model is currently not implemented correctly, please see a screenshot of the error below.
Thanks!
![Seisbanch_error](https://github.com/seisbench/seisbench/assets/95279442/a76a2b24-62e6-4dfc-aed7-f1300a985881)

**Comment by yetinam** [comment]
A related bug is in the last line of the tutorial notebook with `details=True`
