### ISSUE TITLE
Overlap argument in PhaseNet class ignored

### ISSUE THREAD

**Issue by cjunkk** [seisbench/seisbench#243]
Hi,
while using PhaseNet class in Seisbench 0.5.0 with overlap argument

> picker = sbm.PhaseNet.from_pretrained("instance")
> if torch.cuda.is_available():
>     picker.cuda()
> picks = picker.classify(stream, batch_size=256, ovelap=2800, P_threshold=0.3, S_threshold=0.3).picks

I got the following:

> seisbench | WARNING | Unknown argument 'ovelap' will be ignored.

The overlap argument worked properly in the previous release.

Carlo

**Comment by yetinam** [comment]
I think you made a typo. It's `overlap` not `ovelap`. Feel free to reopen the issue if I'm wrong.
