### ISSUE TITLE
Invalid URL. Request returned status code 500.

### ISSUE THREAD

**Issue by ikahbasi** [seisbench/seisbench#246]
Hi,
There is a problem when a pre-trained model is downloaded.

![Screenshot from 2023-11-07 16-17-16](https://github.com/seisbench/seisbench/assets/47061763/7b86e2d7-f3cb-4469-8018-f2e2d7d0216b)

**Comment by yetinam** [comment]
Hi, thanks for making us aware. There seems to be a server error. Please try again later.

**Comment by ikahbasi** [comment]
The problem was fixed.
Thanks.
