### ISSUE TITLE
How to transfer the pre-trained models to another PC

### ISSUE THREAD

**Issue by ikahbasi** [seisbench/seisbench#247]
Greetings.
Could you please tell me how to access the pre-trained models that I have downloaded?
Where are these files stored on the computer?

I am interested in creating backups and transferring these files to other computers that have SiesBench.
This will prevent me from re-downloading the pre-trained models.

**Comment by yetinam** [comment]
The files are stored in the local seisbench cache. You can find the path with `python -c "import seisbench;print(seisbench.cache_root)"`. By default it should be `~/.seisbench`.

**Comment by ikahbasi** [comment]
Great!
Thanks a lot!
