### ISSUE TITLE
In the file "metadata.csv" of dataset, which columns are not necessary for training phase picking models?

### ISSUE THREAD

**Issue by Dong6Jx** [seisbench/seisbench#249]
In the file "metadata.csv" of dataset, which columns are not necessary for training phase picking models?

**Comment by yetinam** [comment]
Hi @Dong6Jx ,
thanks for your interest. The metadata format is flexible, i.e., there can be arbitrarily many columns. For training a phase picking model, only a few are necessary. You'll need the technical one (trace_name, trace_component_order, trace_sampling_rate_hz, chunk) and the ones describing the picks (trace_*_arrival_sample). That should be sufficient. May I ask what prompts your question?

**Comment by Dong6Jx** [comment]
Hi @yetinam ,
thank you for your reply! I'm making my own dataset, but I'm missing some information and I'd like to know if this missing  information is necessary for training a phase picking model. This prompts my question.
