### ISSUE TITLE
Param "scale" in class GaussianNoise

### ISSUE THREAD

**Issue by Antonio-Maraglino** [seisbench/seisbench#266]
Hi, in the augmentations there is a class called GaussianNoise. How can I find the value of the "scale" parameter knowing the standard deviation? (I ask because it says that you need to know the input signal which is usually not known)
Are there also other methods to calculate the parameter "scale"?
using standard parameters I get this:
![Screenshot 2024-01-30 114539](https://github.com/seisbench/seisbench/assets/103511220/8cabc536-a600-429c-95d4-2008472cd50d)
![Screenshot 2024-01-30 114546](https://github.com/seisbench/seisbench/assets/103511220/d977e82e-13eb-45ae-ace3-410ad9f6dd54)

**Comment by yetinam** [comment]
Hi @Antonio-Maraglino ,
the default value for scale is `(0, 0.15)`, i.e., the noise scale will be a uniform random number between 0 and 0.15 times the maximum of the trace. The actual noise at each point will then be a Gaussian with the noise scale as standard deviation. Dose that answer your question?

**Comment by Antonio-Maraglino** [comment]
Thanks, great. But I didn't understand how to use the function if I only know the standard deviation at a certain frequency. Would it make sense to use 3*standard deviation as the maximum value of the scale?

**Comment by yetinam** [comment]
The standard deviation is automatically computed inside the function, so you don't actually know it. It does not take different frequencies into account. 3 * standard deviation seems like a rather high value. The function is actually internally very simple. Everything happens in these 3 lines:
https://github.com/seisbench/seisbench/blob/61ac2df822249fc16b62dfe7da1779ec2e8255bf/seisbench/generate/augmentation.py#L665-L667
