### ISSUE TITLE
Filter problems using InstanceCountsCombined to train PhaseNet

### ISSUE THREAD

**Issue by RossFon** [seisbench/seisbench#267]
Hi, 
I'm trying to train PhaseNet using INSTANCE dataset by means of seisbench tool.
I've already used InstanceCounts options and I've filtered the dataset for my goal. It worked.
Now I would like to use the InstanceCountsCombined and using the same command I received an error. 
I'm attaching the code below. Any suggestions? Thank you!
I'm using the following packages versions:
Seisbench:   0.4.0
torch: 2.1.0+cu121
pandas: 1.5.0
numpy: 1.26.1

```
import os
import h5py
from pathlib import Path

import seisbench as sb
import seisbench.data as sbd
import seisbench.models as sbm
import seisbench.generate as sbg
from seisbench.util import worker_seeding

import numpy as np
import pandas as pd

import torch
from torch.utils.data import DataLoader
data_all = sbd.InstanceCountsCombined(sampling_rate=100.0, cache="full")
print("LENGTH of DATABASE:  %d" % len(data_all.metadata))
data_all.metadata.reset_index(drop=True, inplace=True)
mask = (data_all.metadata['station_channels'] == 'HH') | (data_all.metadata['station_channels'] == 'EH') & (data_all.metadata['trace_dt_s'] == 0.01) 
data_all.filter(mask)
print("NEW LENGTH: %d" % len(data_all.metadata))
```
Edit (yetinam): small formatting update

**Comment by yetinam** [comment]
Hi @RossFon ,
thanks for your report. Could you provide the error trace you get?

**Comment by RossFon** [comment]
Thanks @yetinam for the support. This is the error:


/home/fonzetti/miniconda3/envs/seis_sb04/lib/python3.11/site-packages/seisbench/data/base.py:833: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  self._metadata = self._metadata[mask]

---------------------------------------------------------------------------
IndexingError                             Traceback (most recent call last)
Cell In[5], line 5
      3 data_all.metadata.reset_index(drop=True, inplace=True)
      4 mask = (data_all.metadata['station_channels'] == 'HH') | (data_all.metadata['station_channels'] == 'EH') & (data_all.metadata['trace_dt_s'] == 0.01) 
----> 5 data_all.filter(mask)
      6 print("NEW LENGTH: %d" % len(data_all.metadata))

File ~/miniconda3/envs/seis_sb04/lib/python3.11/site-packages/seisbench/data/base.py:1935, in MultiWaveformDataset.filter(self, mask, inplace)
   1933 if inplace:
   1934     for submask, dataset in zip(submasks, self.datasets):
-> 1935         dataset.filter(submask, inplace=True)
   1936     # Calculate new metadata
   1937     self._metadata = pd.concat(x.metadata for x in self.datasets)

File ~/miniconda3/envs/seis_sb04/lib/python3.11/site-packages/seisbench/data/base.py:833, in WaveformDataset.filter(self, mask, inplace)
    812 """
    813 Filters dataset, e.g. by distance/magnitude/..., using a binary mask.
    814 Default behaviour is to perform inplace filtering, directly changing the
   (...)
    830 :return: None if inplace=True, otherwise the filtered dataset.
    831 """
    832 if inplace:
--> 833     self._metadata = self._metadata[mask]
    834     self._evict_cache()
    835     self._build_trace_name_to_idx_dict()

File ~/miniconda3/envs/seis_sb04/lib/python3.11/site-packages/pandas/core/frame.py:3796, in DataFrame.__getitem__(self, key)
   3794 # Do we have a (boolean) 1d indexer?
   3795 if com.is_bool_indexer(key):
-> 3796     return self._getitem_bool_array(key)
   3798 # We are left with two options: a single key, and a collection of keys,
   3799 # We interpret tuples as collections only for non-MultiIndex
   3800 is_single_key = isinstance(key, tuple) or not is_list_like(key)

File ~/miniconda3/envs/seis_sb04/lib/python3.11/site-packages/pandas/core/frame.py:3849, in DataFrame._getitem_bool_array(self, key)
   3843     raise ValueError(
   3844         f"Item wrong length {len(key)} instead of {len(self.index)}."
   3845     )
   3847 # check_bool_indexer will throw exception if Series key cannot
   3848 # be reindexed to match DataFrame rows
-> 3849 key = check_bool_indexer(self.index, key)
   3850 indexer = key.nonzero()[0]
   3851 return self._take_with_is_copy(indexer, axis=0)

File ~/miniconda3/envs/seis_sb04/lib/python3.11/site-packages/pandas/core/indexing.py:2548, in check_bool_indexer(index, key)
   2546 indexer = result.index.get_indexer_for(index)
   2547 if -1 in indexer:
-> 2548     raise IndexingError(
   2549         "Unalignable boolean Series provided as "
   2550         "indexer (index of the boolean Series and of "
   2551         "the indexed object do not match)."
   2552     )
   2554 result = result.take(indexer)
   2556 # fall through for boolean

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

**Comment by yetinam** [comment]
Looks like an index issue. Can you replace the line `data_all.filter(mask)` with `data_all.filter(mask.values)`? This will avoid indexing issues as the mask is interpreted as a positional index (as it should be) and not as a pandas series.

**Comment by RossFon** [comment]
Ok! Thanks! It works! Thank you @yetinam
