### ISSUE TITLE
model.annotate from GenericGenerator

### ISSUE THREAD

**Issue by Antonio-Maraglino** [seisbench/seisbench#268]
Hi, i want to use model.annotate (in order to get  P and S peaks) with a waveform from a GenericGenerator (which i added 2 augmentations). I tried to use pretrained model (on 'instance') of EQ_transformer.

**Comment by yetinam** [comment]
Hi @Antonio-Maraglino ,
there is no way in SeisBench to pipe the output of a GenericGenerator into `annotate` as these are different interfaces. `annotate` takes obspy streams as input, it is intended for applying a model to waveform data. The `GenericGenerators` works on numpy arrays and is intended for model training.

**Comment by Antonio-Maraglino** [comment]
ok, I had assumed so. I also tried to convert NumPy array into a stream but i failed, it's possible to do it correctly? Or is there a way to obtain peaks from generator without model.annotate?

**Comment by yetinam** [comment]
Yes, you can convert numpy arrays to streams. To do so, you will need to create the individual `obspy.Trace` objects and set the metadata correctly. To pass arrays to SeisBench models, use their PyTorch interface, i.e., the forward function accessed through `model(X)`. Please bear in mind that this will require you to apply appropriate preprocessing and cut the trace to the correct length.

**Comment by Antonio-Maraglino** [comment]
Thank you for the help !(again :D)
