### ISSUE TITLE
Augmentation for Xr

### ISSUE THREAD

**Issue by Antonio-Maraglino** [seisbench/seisbench#270]
I use the agumentation on the generator to add noise to the samples, creating a new element  Xr. How can i apply the others augmentations to Xr?
The sample after the augmentations is a dict with X, y and Xr but just X is modified and not Xr.

**Comment by yetinam** [comment]
Most augmentations have a `key` argument, so you can just set `key="Xr"` when creating the augmentation. If you want to apply the same augmentation to `X` and `Xr` you'll have to create it twice though.
