### ISSUE TITLE
Seisbench is extremely slow when there  are  many gaps in a stream

### ISSUE THREAD

**Issue by zhong-yy** [seisbench/seisbench#273]
Here is an example of picking on a 1-day stream with > 5000 traces.

```python
from obspy import UTCDateTime, read, Stream
import pandas as pd
import seisbench.models as sbm
import seisbench.util as sbu
import time
import datetime
from obspy.clients.fdsn import Client

if __name__ == "__main__":
    code_start_time = time.perf_counter()
    client=Client("IRIS")
    stream=client.get_waveforms(network="AT",station="AKUT",location="",channel="BH*",starttime=UTCDateTime("20230803T000000Z"),endtime=UTCDateTime("20230804T000000Z"))    
    print(f"{len(stream)} traces")
    picker=sbm.EQTransformer.from_pretrained("instance")
    picker.cuda()
    # merge, resample, demean are performed internally
    # https://github.com/seisbench/seisbench/blob/61ac2df822249fc16b62dfe7da1779ec2e8255bf/seisbench/models/base.py#L1015
    # https://github.com/seisbench/seisbench/blob/572c0cad13193c1903d00e2366ed9322e076c43a/seisbench/models/base.py#L2002-L2020
    # https://github.com/seisbench/seisbench/blob/572c0cad13193c1903d00e2366ed9322e076c43a/seisbench/models/eqtransformer.py#L293
    picks = picker.classify(
                    stream,
                    batch_size=8192,
                    overlap=5500,
                    blinding=(500, 500),
                    stacking="avg",
                    parallelism=None, # https://github.com/seisbench/seisbench/issues/272
                    P_threshold=0.22,
                    S_threshold=0.22,
                    copy=False # copy: If true, copies the input stream. Otherwise, the input stream is modified in place. See https://github.com/seisbench/seisbench/commit/862d9ee708c2c3e737da4e90ab3355471aa01ecf
                ).picks
    
    def picklist2df(picks: sbu.PickList):
        def pick2dict(p: sbu.Pick):
            return {
                "trace_id": p.trace_id,
                "start_time": p.start_time,
                "end_time": p.end_time,
                "peak_time": p.peak_time,
                "peak_value": p.peak_value,
                "phase": p.phase,
            }

        pick_df = [pick2dict(p) for p in picks]
        pick_df = pd.DataFrame(pick_df)
        return pick_df
    pick_df = picklist2df(picks)
    pick_df.to_csv("test_output.csv")


    running_time = str(
            datetime.timedelta(seconds=time.perf_counter() - code_start_time)
        )
    print(f"Running time: {running_time}")
```

Picking on a fragmented trace is much slower than on a continuous trace. Is there any way to speed up picking on such kind of traces?

Maybe merging the fragmented trace into a single trace can help. However, internally, the stream is merged using method -1, in which gaps are not filled. I suppose there must be some reason of doing so. May I ask what is the consideration for using merging method -1 instead of filling gaps with 0? Is it because filling gaps can result in false picks at the boundaries of gaps?

**Comment by yetinam** [comment]
Hi @zhong-yy ,

thanks for bringing this up. I've stumbled across this as well at some point. I'm not totally certain what causes the bad run times. My suspicions are either the preprocessing with obspy (applied to each trace in the stream) or the packing into arrays. I've so far decided not to do anything about this because fragmented traces are a pretty clear anti-pattern.

Regarding how to handle this situation. First, you could just throw away fragmented data. I'd argue that it's in most cases anyhow badly broken and should not be used. Second, as you suggested you can fill gaps. The reason SeisBench does not do this internally is that it could lead to unexpected outcomes. However, it's absolutely possible to do this before passing the stream to SeisBench. If the data is not too bad, this might work well. Some models have even been trained to handle gaps in the input.

**Comment by zhong-yy** [comment]
Thank you for the explanation @yetinam 

I incline to keep fragmented data because they are not uncommon. I also found filling the gaps can greatly reduce running times. However, a model can sometimes predict a lot of pick within gaps if I fill the gaps.

For example, here is a one-day waveform with gaps filled with 0
```python
st=client.get_waveforms(network="AV",station="AHB",location="",channel="BH*",starttime=UTCDateTime("2021-11-27T00:00:13.100000Z"),endtime=UTCDateTime("2021-11-28T00:00:12.980000Z"))
```
![image](https://github.com/seisbench/seisbench/assets/38816011/ef6f2397-debb-4cdf-816f-e04d5607bc1b)

The annotation computed by the EQTransformer trained on INSTANCE is
![image](https://github.com/seisbench/seisbench/assets/38816011/9f59f705-1d92-471a-bc78-30891aa73aec)

There are many picks within the gap.

It seems that resampling the waveform may lead to some fake events in the gap with very small amplitude.
![image](https://github.com/seisbench/seisbench/assets/38816011/14be34d0-5897-429c-8e3a-b8b916ab198b)


[Here is a minimal working example.](https://github.com/seisbench/seisbench/files/14345811/picks_in_gap_mwe.zip)

**Comment by yetinam** [comment]
Hi @zhong-yy , that's a very interesting example. I would suspect that the introduction of events after resampling is a filtering artifact. The clean way would be first to resample and then to fill in the gaps. I admit, when speaking about fragmented traces I was thinking rather of traces with lots of small gaps. Is the example above (with apparently 4 different chunks) a runtime problem for SeisBench? Or are there actually lots of smaller gaps not visible in the figures?

**Comment by zhong-yy** [comment]
Thank you for the quick reply @yetinam , 

Yes, there are only 4 chunks in the figures in this example. In some other cases, there are lots of small gaps.  For example
```python
client=Client("IRIS")
st=client.get_waveforms(network="AT",station="AKUT",location="",channel="BH*",starttime=UTCDateTime("20230803T000000Z"),endtime=UTCDateTime("20230804T000000Z"))
print(len(st))
```

Currently, I deal with all the data in the same way.  I can also try filling the gaps only when there are more than a certain number of traces, but I don't know how many gaps will lead to a runtime problem.

**Comment by yetinam** [comment]
Maybe you could only fill gaps below a certain length? And then discard all traces that do not have at least 3000 samples. That should already keep the number in check.

I'm closing this issue here. For now, I think there is no good way of handling this inside SeisBench that is adequate for all users. Instead, I think in the case of bad data users will need to preprocess it themselves first.
