### ISSUE TITLE
Integration of OBSTransformer model into Seisbench

### ISSUE THREAD

**Issue by alirezaniki** [seisbench/seisbench#279]
Hello.

We recently developed a new seismic phase picker for Ocean Bottom Seismometer data at Dalhousie University using transfer learning and autolabelling. The paper was recently published in GJI, where we cited Seisbench and expressed our willingness for this integration. The model is based on EQTransformer, and the dataset is built in the format of the STEAD dataset. We would deeply appreciate your opinion on this, as this integration would significantly benefit the community. Below are the links to the paper and the GitHub repository that is home to OBSTransformer.
https://doi.org/10.1093/gji/ggae049
https://github.com/alirezaniki/OBSTransformer

Best Regards,
Dalquake Group.

**Comment by yetinam** [comment]
Hi @alirezaniki ,

congratulations for the publication! I've seen the work and I think OBSTransformer and your dataset would be a great addition to SeisBench. It would a nice way to complement our existing work on PickBlue. Given your implementation is based on EQTransformer and your dataset has STEAD format, I think the amount of work should be manageable. I'll give some details below.

**Dataset**: For the dataset, the data needs to be converted to SeisBench format. A good starting point should be the [conversion script for STEAD](https://github.com/seisbench/seisbench/blob/7119db6aa3a95b1e9a6e4427baaa0e775cc0e1e0/seisbench/data/stead.py#L31). If your data is exactly in this format, it should run out of the box. Probably your metadata columns will be slightly different, so you'd have to adjust this. Other things to validate are component order and sampling rate. Once done, you'd write a simple wrapper class and send me the data, so I can upload it to our servers.

**Model**: For the model, as far as I remember you're using the architecture of EQTransformer. Have you modified it in any way? If not, the only thing to do is to convert the weights from tensorflow to pytorch. That's a little tedious, but as we've already done it for EQTransformer, there are [Jupyter notebooks](https://github.com/seisbench/seisbench/tree/main/contrib/model_conversion) that should get you most of the way (or even all the way if you're lucky). Once you have the converted weights, I can help you write the json config file and upload everything to the SeisBench repo. It might make sense to create a wrapper class around it just to overwrite the citation information and make sure the weights are properly separated.

Lastly, I'd recommend to separate model and dataset into different PRs just to avoid too large code chunks. Feel free to ask any further questions. I'm looking forward to your contribution!

**Comment by alirezaniki** [comment]
Dear @yetinam 

I used the material you introduced above to convert the dataset and model to the desired formats. The code worked perfectly for the dataset; I could convert it to the seisbench format (two files generated, namely metadata.csv and waveforms.hdf5). 
I also managed to generate a .pt file from my model, which should contain the model weights (?). Please note that I only executed the codes in the jupyter notebook up to the line below:
**Run in an EQTransformer compatible env - results loaded**

I would really appreciate your help with the JSON config file and citaion configuration. Please let me know how I can proceed with sharing the data and files with you.

**Comment by yetinam** [comment]
Hi @alirezaniki ,

that's great news! Can you tell me how big your data is? For sharing it, you can upload it somewhere and send me the link per mail. If that doesn't work, I can give you access to an FTP server at our institute where you can upload it. In that case, please send me a mail so I can share the login detail with you.

Regarding the .pt file, yes, that is containing the model weight. I would however ask you to run the next part of the notebook as well. This part is essential because it actually validates that the models in pytorch and tensorflow are identical (up to numerical precision).

For the json file, you should start of add the one for EQTransformer original. It should look something like the one below (without the comments).
```json
{
# Check that the order of input components and output phases are correct
  "component_order": "ZNE",
  "phases": "NPS",
  "norm": "std" # Check  if you normalize the input by the peak value of the std
  "docstring": "", # Provide a short description, a reference, and possibly your mail address
  "seisbench_requirement": "0.7.0",
  "model_args": {
       # This defines which exact architecture for EQTransformer you are using
  	"original_compatible": "conservative",
  	"lstm_blocks": 3,
       # If you use a filter, you need to define the arguments here
	"filter_args": ["bandpass"],
	"filter_kwargs": {
		"freqmin": 1,
		"freqmax": 45,
		"corners": 2,
		"zerophase": true
	}
  },
  "version": "1"
}
```

**Comment by alirezaniki** [comment]
Dear @yetinam 

Thank you for providing me with the code. I will go through it once I am done with the notebook file. Files are ~5 GB large. I will send you a Google Drive link once I am finished with preprocessing. (One thing about the dataset is that traces are all normalized to their standard deviation, so I hope it's not a problem.) 
As you suggested, I kept executing the code further to see if the TensorFlow and PyTorch versions had the same outputs. I got the following figure:

![Screenshot from 2024-03-22 18-55-21](https://github.com/seisbench/seisbench/assets/24492517/212c86c0-a762-47e2-96d8-e4243be23836)

![Screenshot from 2024-03-22 18-25-00](https://github.com/seisbench/seisbench/assets/24492517/2b680cfb-40b5-41da-97cc-a09153b01d9f)

Given the discrepancies, I kept moving but got an error for one of the cells. See below:
```
model.pick_attentions[0].eps = 1e-5

model.eval()
with torch.no_grad():
    det, p, s, layerout = model(torch.tensor(wv[:, [2, 1, 0]], dtype=torch.float32))
    # For weights matrix needs to be permuted
    layerout = layerout.permute(0, 2, 1)
    layerout = layerout.numpy()
# Compare the first convolution layer
# layerout = intermediaries[7].numpy()
print(layerout.shape)
plt.plot(tf_p[0, :, 0] - p.numpy()[0, :])

#~~~~~~~~~~~
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_3518322/325614632.py in <module>
      4 model.eval()
      5 with torch.no_grad():
----> 6     det, p, s, layerout = model(torch.tensor(wv[:, [2, 1, 0]], dtype=torch.float32))
      7     # For weights matrix needs to be permuted
      8     layerout = layerout.permute(0, 2, 1)

ValueError: not enough values to unpack (expected 4, got 3)
```
The code expects four outputs; however, model outputs are only three. Any ideas?

**Comment by yetinam** [comment]
Hi @alirezaniki ,
thanks for the update! No worries about the std normalisation of the data. That's the case for some of the datasets.

Regarding the differences between tf and pytorch, assuming the first plot you show is the difference between the outputs, is absolutely no problem. 1e-6 is within the acceptable error of numerical accuracy.

**Comment by alirezaniki** [comment]
Hi @yetinam 

That's awesome, then! I am ready to send you the dataset, model, and modified config file you provided. Could you please share your email address with me?
