### ISSUE TITLE
Doubt about characteristics of training data - EQTransformer

### ISSUE THREAD

**Issue by sfpoveda** [seisbench/seisbench#285]
Hi,

Is there exist a summary of the charcteristics of the training data used in each model? For example, how large are the waveforms used? what the filtering of the waveforms is? what the sampling rate is?  I have not found it yet. Do I have to look for them in the corresponding paper of each model? 

The thing is am interested in re-training EQTransfromer by applying transfer learning to the last layers of the model, but as I'll use pretrained weights that considered a specific dataset with a specific sampling rate and specific filters, I would like to apply that same preprocessing steps to my data so that they follow the roughly the same standard/distribution of the original dataset.

**Comment by yetinam** [comment]
Hi @sfpoveda , most information is provided in the attribute `weights_docstring`, once you've loaded a pretrained model. Most models in SeisBench result from our benchmark. The full training scripts are available [here](https://github.com/seisbench/pick-benchmark/) if you want to fully reproduce the processing. However, for transfer learning I'd usually assume that an exactly identical processing is not required.
