### ISSUE TITLE
Assistance with getting access to the repository through firewall?

### ISSUE THREAD

**Issue by shawnboltz** [seisbench/seisbench#288]
I have been trying to get access to the dCache repository through my corporate firewall and my IT department seems to be having some trouble with it (the rules are in place where it should be open on our end, but for some reason connection attempts are continuing to time out). Would someone from the dev team be able to assist in seeing if we can figure out where our attempts to reach out to it are getting blocked?

Thank you!

**Comment by yetinam** [comment]
Hi @shawnboltz ,

thanks for your interest in SeisBench. For all I know, our repository does not block any outside traffic, so I fear the configuration problem is on the side of your firewall or maybe ISP. The address you need to be able to reach is `https://hifis-storage.desy.de:2880/`. Please note that this is port `2880`, which is nonstandard.

From our side, we have put in place a backup repository, running on a standard port. To switch to using it, just set `seisbench.use_backup_repository()`. You can find more detail on the matter [here](https://seisbench.readthedocs.io/en/stable/pages/installation_and_usage.html#configuring-the-remote-repository). The backup repository is a little slower but unless you access the biggest datasets, this should not cause much trouble.

**Comment by yetinam** [comment]
Closing this for now. Feel free to reopen if the problem persists.
