### ISSUE TITLE
Inquiry Regarding Running the Software on a large Dataset

### ISSUE THREAD

**Issue by jtaxo** [seisbench/seisbench#290]
Dear Jannes,

I hope this message finds you well. 
As a user and supporter of your project, I've encountered a scenario where I could benefit from your expertise.

Specifically, I am working on collecting data from multiple stations over the course of a full year. My aim is to obtain picks and establish associations within this dataset. However, I am faced with the challenge of devising an effective methodology for this task.

Given your experience with the project and its underlying architecture, I was wondering if you could provide any insights or suggestions on how best to approach this data collection process.

Thank you very much for your time and consideration.

Best regards,
João Cartaxo

**Comment by yetinam** [comment]
Hi @jtaxo ,

thanks for your interest in SeisBench. As a general pattern for processing large datasets, the following has proven a good approach:

- Make the data locally available, for example, with the MassDownloader from obspy.
- For picking, iterate over the data in reasonable chunks. A typical size might be daily waveforms per stations. The only thing to ensure is that all components of a station are passed to the `classify` call at once.
- Collect the picks and pass them to the associator. Here, I'd again advice chunking. Note that chunking here can only happen by time, e.g., per day, as picks from all stations are needed at once by the associator.

We're working on a toolbox to handle all of this for you, but it will take a few more months.
