### ISSUE TITLE
directory for the datasets to be cached in 

### ISSUE THREAD

**Issue by jsbyrnes** [seisbench/seisbench#293]
I currently cannot download the data on my university's HPC system because the datasets are being cached in the home directory, where there is a disk quota. We have another directory with plenty of storage space, but I cannot figure out how to change the location of seisbench's cache so that it is not in ~/.seisbench - is this possible or does this feature need to be implemented?

**Comment by jsbyrnes** [comment]
In the meantime I've tried modifying seisbench.cache_root to a local directory, and then if initialize a data set that isn't cache by doing "import seisbench.data as sbd; sbd.OBS()", the data starts downloading in %HOME/.seisbench anyway.

**Comment by yetinam** [comment]
Hi @jsbyrnes ,

Thanks for your question. To change the caching directory, just set the environment variable `SEISBENCH_CACHE_ROOT` to the desired path. You can do this, for example, in your .bashrc file.

Alternatively, you can replace the `~/.seisbench` directory with a symlink to the intended storage folder.

**Comment by jsbyrnes** [comment]
Fantastic, thank you!
