### ISSUE TITLE
Add volpick model to seisbench

### ISSUE THREAD

**Issue by zhong-yy** [seisbench/seisbench#297]
Hi Dr. Münchmeyer,

We've recently used seisbench to retrain PhaseNet and EQTransformer on volcano-tectonic and long-periods earthquakes from Alaska, Hawaii and Japan. We showed that our model can better pick volcanic earthquakes by comparing our retrained models with the original PhaseNet and EQTransformer weights and the model weights trained on INSTANCE.  The models were also tested on cross-domain testing waveforms from volcanoes along the Cascadia subduction zone and tectonic low-frequency earthquakes along the Nankai trough. A test on the INSTANCE dataset suggested our models can also work for regular earthquakes.  The paper was just accepted in GRL. The models are preserved in this repository: https://github.com/zhong-yy/volpick.  The metadata of the dataset is preserved in Zenodo: https://zenodo.org/records/11206597.

We think it might be helpful if our models and dataset can be integrated into seisbench.

Best regards,
Yiyuan Zhong

**Comment by yetinam** [comment]
Hi Yiyuan,

congratulations on your GRL paper and thanks a lot for providing the weights to SeisBench! I've uploaded the weights from your to the SeisBench repository now, so they are available through `from_pretrained` directly and visible on `list_pretrained`. I've long hoped to add a volcano model to SeisBench, so it's great to get this addition. As we've quite a zoo of models for different use cases by now, I've opened #298 to add guidance on how to choose models.

Just to check, for your training datasets, only the metadata is public, but the waveforms are not? If you should choose to make the waveforms public as well, I'd be happy to include them in SeisBench.

Once again, thanks a lot for your contribution!

**Comment by zhong-yy** [comment]
Thank you for adding our models to SeisBench @yetinam 

We didn't upload the waveforms because the files are large and [NIED](https://www.hinet.bosai.go.jp/about_data/?LANG=en#M9) does allow redistributing waveforms downloaded from Japan. 

Here is the link to the dataset excluding waveforms from Japan: [vcseis](https://mycuhk-my.sharepoint.com/:u:/g/personal/1155187577_link_cuhk_edu_hk/ERDz2m9BsE5PiK81hH3wQeQBzmw7SQj8GlN2591nQ2sPpQ?e=sdaWg3). 

```
├── chunks
├── metadata_ak_lp.csv      # Long-period earthquakes (LP) from Alaska
├── metadata_aknoise.csv    # Visually inspected noise waveforms from Alaska
├── metadata_ak_rg.csv      # Regular earthquakes (volcano-tectonic earthquakes,VT) from Alaska
├── metadata_cascade_lp.csv # Long-period earthquakes the Cascade Range
├── metadata_cascade_vt.csv # Regular earthquakes near volcanoes from the Cascade Range
├── metadata_hw12t21_lp.csv # Long-period earthquakes from Hawaii 
├── metadata_hw12t21_rg.csv # Regular earthquakes from Hawaii
├── metadata_hwnoise.csv    # Visually inspected noise waveforms from Hawaii
├── metadata_ncedc_lp.csv   # Long-period earthquakes Northern California (NCEDC)
├── metadata_ncedc_vt.csv   # Regular earthquakes near volcanoes from Northern California (NCEDC)
└── waveforms_*.hdf5        # waveform files
```
