### ISSUE TITLE
Multiple picks in one trace - Seisbench format

### ISSUE THREAD

**Issue by sfpoveda** [seisbench/seisbench#309]
Hi,

I am converting my datset to Seisbench format using the tutorial "03b_creating_a_dataset.ipynb". However, in this tutorial we create one trace for each pick, but I would like sometimes to have two picks in the same trace. Is this possible? How can I do it?

Furthermore, given that there is a way to include more than one pick in the same trace, how can I implement it in the probabilistic labeller of Seisbench so that it generates two probabilistic labellers when there are two picks in the same trace?

**Comment by yetinam** [comment]
Hi @sfpoveda ,
thanks for the question. Indeed, it's better to not create one trace per example but label all arrivals. There's actually even a feature request to update the tutorial #153. In the meantime, you can have a look at the dataset conversion scripts included in the code, for example, [this one](https://github.com/seisbench/seisbench/blob/5bccdf4d079c69c8f23450e5d446aefc40bbde18/seisbench/data/ethz.py#L109).

One question is, if you only want to have picks with different phase labels (P and S) within one trace, or also picks with the same phase labels (multiple P phases). The first case is straightforward, you just write them to the respective columns. For the second case, the best workaround is to create additional columns like `trace_P_1_arrival_sample`, `trace_P_2_arrival_sample`, ... . As long as no trace has excessive amounts of phases, this should not cause any trouble.

For the ProbablisticLabeller, it will by default label all phases, even with the same phase label. You'll just need to make sure to pass the right dictionary to `label_columns`, mapping the column names to the right phases.

Feel free to reopen the issue if you have further questions.
