### ISSUE TITLE
A suggestion on the use of GPU.

### ISSUE THREAD

**Issue by JUNZHU-SEIS** [seisbench/seisbench#310]
If I have multiple GPU cards, how to assign a specifi GPU card, e.g., cuda:1, to acclerate PhaseNet?
This feature seems missing in the current version. It might be useful to include this feature, especially if "cuda:0" (the first GPU card) has already been used by the other users in a server.
![image](https://github.com/user-attachments/assets/5a96fe82-f636-4b46-83cb-7fb1123f19e1)

**Comment by yetinam** [comment]
You can select the GPU in (at least) two different ways. First, you can do `model.to(device)` and specify the GPU through the device variable. Second, you can start your environment with the `CUDA_VISIBLE_DEVICES` environment variable to restrict which GPUs the process sees.

**Comment by JUNZHU-SEIS** [comment]
Thanks for your quick reply. As a side note, I have tried both ways. But only setting `CUDA_VISIBLE_DEVICES` works well, `model.to(device)` results in different output from `model.cuda()`.
