### ISSUE TITLE
Single component data for PhaseNet

### ISSUE THREAD

**Issue by chenglongduan** [seisbench/seisbench#311]
In my previous practice, I had three-component data (e.g. BHE, BHN, BHZ) as input to SeisBench to perform PhaseNet picking. It worked successfully to return Phasenet_P, Phasenet_S and Phasenet_N.

However, for some nodal arrays, I only have single-component data (e.g. DPZ). Can PhaseNet in SeisBench work as well in terms of this case? If not, do you have any suggestions to solve this issue?

Thanks!

**Comment by chenglongduan** [comment]
Looks like I can answer my own question...
I tested myself that single-component data can work using PhaseNet in SeisBench. So it seems the number of data component is not a problem for picking. The only thing I need consider is to have enough data samples. For instance, 1700 data samples (100 Hz sampling rate) as the input causes a warning and empty output. I have to pad the trace until I have 3500 data samples, so that I'll get valid outputs.

**Comment by yetinam** [comment]
Hi @chenglongduan ,
indeed, you can give waveform with fewer components to `annotate`/`classify` if you set `strict=False` (the default). However, from personal experience, picking performance on single components is usually not as good as on multiple components. In particular, I had trouble with an increased number of false positives.
