### ISSUE TITLE
Incorrect Elevation to Depth Transformation in `03c_catalog_seisbench_gamma.ipynb`

### ISSUE THREAD

**Issue by DaDaCheng** [seisbench/seisbench#314]
In the Colab example `03c_catalog_seisbench_gamma.ipynb`, there is an issue with the transformation of elevation to depth. Specifically, the line:

```python
station_df["z(km)"] = station_df["elevation(m)"] / 1e3
```

This transformation should include a negative sign, as depth is typically represented as a negative value when the elevation is above sea level. This correction could be:

```python
station_df["z(km)"] = station_df["elevation(m)"].apply(lambda x: -x / 1e3)
```
which can be seen in the original Gamma repo [here](https://github.com/AI4EPS/GaMMA/blame/d978996dbab9618c38552c8c946d710e2379bbdb/tests/GaMMA.ipynb#L106C17-L106C17).

**Comment by yetinam** [comment]
Great catch, thanks! I've fixed it now.
