### ISSUE TITLE
Phase picking for TXED

### ISSUE THREAD

**Issue by liutianlin0121** [seisbench/seisbench#317]
Hi Jannes,

Thanks a lot for the discussion today!

I did a quick review of samples from the TXED dataset that you mentioned. Perhaps I missed something, but it appears to me that the `sbg.WindowAroundSample` with `phase_dict` in the augmentation module couldn't locate P and S events for the TXED dataset. Specifically, if we run the below code:

```python
import seisbench.data as sbd
import matplotlib.pyplot as plt
import seisbench.generate as sbg
import numpy as np

dataset = sbd.TXED(
      sampling_rate=100,
      component_order='ZNE',
      dimension_order='NCW',
      cache=None
)
train, dev, test = dataset.train_dev_test()

phase_dict = {
    "trace_p_arrival_sample": "P",
    "trace_pP_arrival_sample": "P",
    "trace_P_arrival_sample": "P",
    "trace_P1_arrival_sample": "P",
    "trace_Pg_arrival_sample": "P",
    "trace_Pn_arrival_sample": "P",
    "trace_PmP_arrival_sample": "P",
    "trace_pwP_arrival_sample": "P",
    "trace_pwPm_arrival_sample": "P",
    "trace_s_arrival_sample": "S",
    "trace_S_arrival_sample": "S",
    "trace_S1_arrival_sample": "S",
    "trace_Sg_arrival_sample": "S",
    "trace_SmS_arrival_sample": "S",
    "trace_Sn_arrival_sample": "S",
}

train_generator = sbg.GenericGenerator(train)

augmentations = [
    sbg.WindowAroundSample(
      list(phase_dict.keys()),
      samples_before=3000,
      windowlen=6000,
      selection="random",
      strategy="variable"
    ),
    sbg.RandomWindow(windowlen=3001, strategy="pad"),
    sbg.Normalize(demean_axis=-1, amp_norm_axis=-1, amp_norm_type="std"),
    sbg.ChangeDtype(np.float32),
    sbg.ProbabilisticLabeller(
      label_columns=phase_dict, sigma=30, dim=0,
    )
]

train_generator.add_augmentations(augmentations)



for i in range(20):
  sample = train_generator[i]
  waveform = sample["X"]
  fig = plt.figure(figsize=(7, 5))
  axs = fig.subplots(2, 1, sharex=True, gridspec_kw={"hspace": 0, "height_ratios": [3, 1]})
  axs[0].plot(sample["X"].T);
  axs[1].plot(sample["y"].T);
  plt.title(f'waveform index {i}')

```

Then the plots are made:

![image](https://github.com/user-attachments/assets/a50b1a2b-ae4d-4691-8b51-9ff2f366f0ad)

![image](https://github.com/user-attachments/assets/28860c60-4349-4b72-88fb-080a1cfe50f7)

![image](https://github.com/user-attachments/assets/3c820308-4e94-4a1c-a295-bc3384a8946d)

My understanding is that `WindowAroundSample` should locate the P and S onset and create a window around that. But from the waveforms and their corresponding labels, there is no P and S onset in the windows. This approach works for all other datasets that I tried, but not for TXED. Do you think this is an abnormal behavior?

Thanks!

Tianlin

**Comment by yetinam** [comment]
Hi @liutianlin0121 ,

sorry for the late reply! I think the problem is that the first examples in the TXED dataset are all noise. This is listed in `metadata["trace_category"]`. These examples will not contain any phase arrivals. In this case, a random window is returned by `WindowAroundSample`. If you take a later example, it should hopefully work. As an alternative, you can filter the dataset by the column 'trace_category` before giving it to the generator.

Please reopen the issue in case the noise examples are not the explanation for the behaviour.
