### ISSUE TITLE
TXED trace origin time

### ISSUE THREAD

**Issue by JoelBeltranG** [seisbench/seisbench#318]
Hi!
I am trying to work with the TXED dataset but I can't seem to find the origin time of each of the traces. Inside the metadata there is the P and S arrival times as well as the "source_origin_time" but this doesn't seem to be the "trace_start_time". What can I do ?

**Comment by yetinam** [comment]
Hi! As far as I know the TXED dataset does not contain any information on the trace origin time. The original authors did not include this information (see table 1 [here](https://pubs.geoscienceworld.org/ssa/srl/article/95/3/2013/633471/TXED-The-Texas-Earthquake-Dataset-for-AI)). Is there a specific reason why you need this information? It's typically not used for model training.

**Comment by JoelBeltranG** [comment]
Thank you for your response! My goal is to compare the model's P- and S-wave picks with the manually picked P- and S-wave arrival times. That's why I'm looking for information on the trace origin time.

**Comment by yetinam** [comment]
In this case, I think the `trace_P_arrival_sample` and `trace_S_arrival_sample` are what you are looking for. This will tell you at which sample in the trace the manual pick is.

**Comment by JoelBeltranG** [comment]
Thank you for your help! This is exactly what I needed
