### ISSUE TITLE
ContextualVersionConflict: sympy

### ISSUE THREAD

**Issue by mmusalhi** [seisbench/seisbench#320]
I could not run.
from seisbench import EQTransformer

I received the following message:

**ContextualVersionConflict**: (sympy 1.11.1 located at c:\users\user\anaconda3\lib\site-packages) conflicts with the requirement 'sympy==1.13.1; python_version >= "3.9"' from the package {'torch'}.

I installed SymPy version 1.13.1, but I'm experiencing issues.

**Comment by yetinam** [comment]
Hi @mmusalhi ,
I'm not familiar with this issue, but from what I read, it can often be resolved by restarting the runtime. Could you test if restarting the kernel/runtime solves your issue?

If not, can you provide step by step instructions on how to reproduce the issue?

**Comment by yetinam** [comment]
Closing as inactive. Feel free to reopen if the issue persists.
