### ISSUE TITLE
Combining Seismogram Datasets from Parallel Jobs in Seisbench

### ISSUE THREAD

**Issue by wesmail** [seisbench/seisbench#321]
Dear experts

I am using `Instaseis` to simulate seismograms, aiming to generate a large number of events for training. To achieve this efficiently, I would like to leverage parallel jobs on a computer cluster using SLURM. Below is a minimal example of my simulation code:

```
def simulate_event():    
    rec = instaseis.Receiver(latitude=44.06238, longitude=10.59698, network="IV", station="BDI")
    src = instaseis.Source.from_strike_dip_rake(
        latitude=37.77, longitude=15.37, depth_in_m=12000.0, M0=1e+21, strike=32., dip=62., rake=90.
    )
    seismograms = db.get_seismograms(source=src, receiver=rec, components="ZNERT")
    return seismograms, {"src_latitude": src_latitude, "src_longitude": src_longitude, "depth": depth_km}

for n in range(n_events):
    seismogram = simulate_event()
```

For each parallel job, I plan to use `WaveformDataWriter` to store the data, which results in multiple datasets (`metadata_xx.csv` and `waveforms_xx.hdf5`, where `xx` is a unique identifier for each job). Is there a built-in way in `seisbench` to efficiently combine these dataset **chuncks** into a single, unified dataset?

Or can these **chuncks** used efficiently in training instead of combining them?

Thank you in advance for your guidance!

**Comment by yetinam** [comment]
Hi @wesmail ,
Thanks for your question. There are two ways to do this. The first is creating a [MultiWaveformDataset](https://seisbench.readthedocs.io/en/stable/pages/documentation/data.html#seisbench.data.base.MultiWaveformDataset). This automatically combines different datasets. You can achieve this as well by using the + operator on datasets but if you want to combine more than two datasets it's usually better to just create the MultiWaveformDataset directly.

Option two is treating your dataset as chunked. Just store all files in one folder and load the folder as a dataset. SeisBench should automatically discover the different chunks.

I hope this helps. Feel free to follow up and please close the issue if your wuest

**Comment by wesmail** [comment]
Thank you very much @yetinam.

Both worked perfectly well
