### ISSUE TITLE
EQTransformer 

### ISSUE THREAD

**Issue by mmusalhi** [seisbench/seisbench#323]
Hi,  
I am testing EQTransformer, but I received a message, and the result does not show up.

C:\Users\User\anaconda3\lib\site-packages\seisbench\models\base.py:527: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model_weights = torch.load(f"{path_pt}")

I am testing this example

from obspy.clients.fdsn import Client
from obspy import UTCDateTime
import matplotlib.pyplot as plt
from seisbench.models import EQTransformer

client = Client("GFZ")

t= UTCDateTime("2007/01/02 05:48:50")
st= client.get_waveforms(network="CX", station="PB01", location="*", channel="HH?", starttime=t-100, endtime=t+100)

eqt_model=EQTransformer.from_pretrained("original")

eqt_annotation = eqt_model.annotate(st)
eqt_picks= eqt_model.classify(st)

**Comment by yetinam** [comment]
Hi @mmusalhi ,

I tried running your code example on my installation of SeisBench and it works as expected. The variables `eqt_annotation` and `eqt_picks` contain the probability curves and picks. The warning message should not be related to your problem. Could you describe your issue in more detail? Does the code stall while running this code or are the variables not set at the end? In addition, could you provide details on your operating system and SeisBench version?

**Comment by yetinam** [comment]
Could you check if your issue is related to #324 ?

**Comment by mmusalhi** [comment]
I uninstalled SeisBench and then reinstalled it. Now it is working properly. Thank you
