### ISSUE TITLE
EQtransformer (SSL certificate issue)

### ISSUE THREAD

**Issue by nnajafipour** [seisbench/seisbench#324]
Hi everyone,

From friday i have this error when I run my code (seisbench-eqt) :

HTTPSConnectionPool(host='hifis-storage.desy.de', port=2880): Max retries exceeded with url: /Helmholtz/HelmholtzAI/SeisBench/models/v3/eqtransformer (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))

before i run it without any errors.

**Comment by yetinam** [comment]
Hi @nnajafipour ,
thanks for reporting this. Seems like there is a certificate problem with our server. I'll reach out to the sysadmin.

**Comment by yetinam** [comment]
As a workaround, you can use the alternative repository by calling `seisbench.use_backup_repository()`.

**Comment by yetinam** [comment]
I renamed the issue to a more descriptive title. Hope you don't mind.

**Comment by yetinam** [comment]
Should be fixed now. Please reopen the issue if the problem persists.

**Comment by nnajafipour** [comment]
Thanks, Now It works without that line as well.
