### ISSUE TITLE
how to use the LFEDetect

### ISSUE THREAD

**Issue by mujinyang123** [seisbench/seisbench#326]
the LFEDetect is not in sbm.PhaseNet.list_pretrained()
how can i use it?
thanks!

**Comment by yetinam** [comment]
Hi @mujinyang123 ,
the LFEDetect model is implemented as a separate class. Try `sbm.LFEDetect.list_pretrained()` to see available weights. Typically, I'd recommend the `"jcms"` model, i.e., `sbm.LFEDetect.from_pretrained("jcms")`.

**Comment by mujinyang123** [comment]
thanks
