### ISSUE TITLE
Installation via Windows os

### ISSUE THREAD

**Issue by jawooll** [seisbench/seisbench#43]
Currently, there is a dependency error when looking to install the package requirements via pip on Windows machines. This occurs due to compatibility issues with the gdal on Windows. see [here](https://stackoverflow.com/questions/50876702/cant-install-fiona-on-windows), and [here](https://github.com/Toblerity/Fiona/issues/847). When installing, users' will see:

```
Collecting fiona
  Using cached https://files.pythonhosted.org/packages/be/04/31d0a6f03943b1684f32c9b861be40c1fd282468fa6bd54ddf4a774e6b0f/Fiona-1.8.13.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'C:\Python27\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\tarsi\\appdata\\local\\temp\\pip-install-weylhh\\fiona\\setup.py'"'"'; __file__='"'"'c:\\users\\tarsi\\appdata\\local\\temp\\pip-install-weylhh\\fiona\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'c:\users\tarsi\appdata\local\temp\pip-install-weylhh\fiona\pip-egg-info'
         cwd: c:\users\tarsi\appdata\local\temp\pip-install-weylhh\fiona\
    Complete output (1 lines):
    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

As windows machines cannot rely on the gdal-config which is only present on UNIX systems. 

There are workarounds including installing the compatible, Windows-specific wheel files. This just requires some additions to the package install logic in ```setup.py```.

To ensure this is integrated correctly, all os systems can be checked during CI testing. The minor problem with this is that this greatly increases the number of billed hours, and could go over the monthly limit. Once the package is public, however, the number of actions we get is unlimited.

**Comment by yetinam** [comment]
Closed with #47
