### ISSUE TITLE
Contributing - SEDENOSS

### ISSUE THREAD

**Issue by IMGW-univie** [seisbench/seisbench#48]
Dear SeisBench, just heard on ESC2021 about your wonderful SeisBench. I liked how you restructured the research code to actually useable production code. How do I contribute my models? Would you be able to help me out with refactoring to your format? (check our git/source-separation)

**Comment by yetinam** [comment]
Hey, thanks for your interest in contributing to SeisBench! For the basics of contributing to SeisBench, check out the [CONTRIBUTING.md](https://github.com/seisbench/seisbench/blob/main/CONTRIBUTING.md) file. In general, to be included into the SeisBench repository, we require a peer-reviewed publication. As far as I see, SEDENOSS is currently under review, so I'd wait with the merging.

Nonetheless, I'd very much encourage you to already bring your model into SeisBench format and we can merge it once accepted. As a starting point, check out the [documentation of WaveformModel](https://seisbench.readthedocs.io/en/latest/pages/documentation/models.html#seisbench.models.base.WaveformModel), the class your model should be based on. As you are among the first external contributors, I assume documentation still has quite some room for improvement ;-) Therefore, I'd suggest you make yourself familiar with the two documents above, and if you have any open questions, drop me a mail and we can schedule a call to discuss the next steps forward.

**Comment by yetinam** [comment]
Hey @IMGW-univie ,
I saw that SEDENOSS has now been [published in JGR](https://doi.org/10.1029/2021JB023183). Congratulations! Would you still be interested in integrating SEDENOSS into SeisBench?

**Comment by yetinam** [comment]
Closing the issue for now. Feel free to reopen if you'd like to contribute SEDENOSS.
