### ISSUE TITLE
Any workflow or examples of building a new standard seisbench dataset?

### ISSUE THREAD

**Issue by Acidmanc** [seisbench/seisbench#58]
I'm a student and I am very interested about this ML toolbox in seismology, but I am not very familiar with ML and python, I was wondering that is there any workflow or example of converting my own data to a new standard seisbench dataset? I have read the documentation and found some functions about this but still not understand clearily.
Thank you very much.

**Comment by yetinam** [comment]
Hey, thanks for getting in touch! Indeed, there is currently no explicit example on how to get started creating a dataset. Therefore, for now I'd suggest looking at existing examples.
The easiest one is the DummyDataset. You can find the code for conversion here:
https://github.com/seisbench/seisbench/blob/4930e8172ba46a5159975819aaf7ba1409154899/seisbench/data/dummy.py#L24
For a more practical but still rather compact example I'd point you towards the ETHZ dataset:
https://github.com/seisbench/seisbench/blob/4930e8172ba46a5159975819aaf7ba1409154899/seisbench/data/ethz.py#L64

Nonetheless, I think it's a great suggestion to add an example on how to compile a dataset. @jawooll What do you think? Maybe it could be a 02 example notebook on compiling a dataset.

**Comment by jawooll** [comment]
> Hey, thanks for getting in touch! Indeed, there is currently no explicit example on how to get started creating a dataset. Therefore, for now I'd suggest looking at existing examples. The easiest one is the DummyDataset. You can find the code for conversion here:
> 
> https://github.com/seisbench/seisbench/blob/4930e8172ba46a5159975819aaf7ba1409154899/seisbench/data/dummy.py#L24
> 
> 
> For a more practical but still rather compact example I'd point you towards the ETHZ dataset:
> https://github.com/seisbench/seisbench/blob/4930e8172ba46a5159975819aaf7ba1409154899/seisbench/data/ethz.py#L64
> 
> Nonetheless, I think it's a great suggestion to add an example on how to compile a dataset. @jawooll What do you think? Maybe it could be a 02 example notebook on compiling a dataset.

@yetinam good idea, I think so, expanding out the range of examples can only help with getting orientated with the package.

**Comment by Acidmanc** [comment]
Thanks a lot for your kindly reply! I‘m very excited and I am expecting for more examples to help beginners like me to start with this toolbox.
