### ISSUE TITLE
channel and location associated with trace and/or station?

### ISSUE THREAD

**Issue by ftilmann** [seisbench/seisbench#63]
I notice that there is both station_channel and trace_channel as attributes, which seem to be the for the same content and thus seem somewhat redundant. 

Is there any notion which one to be used?  Is station_channel essentially an abbreviation, meaning that these channel names (stripped of the component) apply to all the traces, and trace_channel can be used to distinguish. 

If this is so, I suggest to introduce "trace_location" in a similar spirit (station_location already exists), as we can envisage future datasets where the stream from different 'locations' (usually labelled 00, 10, 20 etc) are used as multi-channel input streams, e.g. when processing borehole data or Strong motion + broadband (which sometime are associated with different location code).

**Comment by yetinam** [comment]
That's a good point, I wasn't aware of this duplication. I'd personally prefer keeping "station_channel" and "station_location" and removing the "trace_*" parameters, because I think it would fit the descriptions of the categories better (see below). What's you opinion @ftilmann @jawooll ?

> "station" contains all information about the station recording the trace, such as station and network code or station location.
> "trace" contains all information and annotations for the trace, such as the start time, the picks or ground motion parameters.

**Comment by jawooll** [comment]
Well spotted Frederik. To be in keeping with our descriptions I'd go with +1 for moving into ```station_*``` and removing channel from ```trace_*``` params.

**Comment by ftilmann** [comment]
I am not so sure. In seismology metadata channel identifier and location are thought of as properties of each channel, as one station will generally have many channels (e.g. short period, long period, and broadband data, each with 3 components, potentially also exotic components like strain, rotation, pressure) and might have several locations (e.g surface sensor and sensor in borehole for HINET, but also sometimes accelerometer and broadband data are given different location designators. On the other hand, in the Seisbench context, the trace_ metadata might contain more ephemeral information (like start time, pick etc), which changes according to the particular event, whereas the channel information only changes when there are changes to the instrumentation.  So lumping classic station and channel metadata  into the station_ variables also makes sense. I would be happy with either way but I guess should be consistent.

**Comment by yetinam** [comment]
I updated the documentation now. After checking with the existing datasets, I decided it's better to keep it listed as `trace_channel`.
