### ISSUE TITLE
Certificate expired for pretrained models

### ISSUE THREAD

**Issue by zoekrauss** [seisbench/seisbench#66]
I am now no longer able to download pretrained models using, for example, the following commands:

`import seisbench.models as sbm`
`model = sbm.DeepDenoiser.from_pretrained("original")`

or 

`model = sbm.EQTransformer.from_pretrained("original")`

Both of these commands raise the following error:

`SSLError: HTTPSConnectionPool(host='[dcache-demo.desy.de](http://dcache-demo.desy.de/)', port=2443): Max retries exceeded with url: /Helmholtz/HelmholtzAI/SeisBench//models/deepdenoiser/original.pt (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))`

I have tried these commands on multiple machines and the same problem arises on each. The certificate appears to have expired within the last few days. What is the solution to this?

Thanks in advance!

**Comment by yetinam** [comment]
Hey @zoekrauss ,
thanks for reporting this! Looks like the certificate expired 3 days ago. I've texted our sysadmin and hope the certificate can be updated soon. If you urgently need any files, you can manually download them from the repository https://dcache-demo.desy.de:2443/Helmholtz/HelmholtzAI/SeisBench/ . You'll have to bypass the expired certificate, for example, by explicitly selecting this in the browser.

**Comment by yetinam** [comment]
The issue should be fixed now. Feel free to reopen if you still experience problems.
