### ISSUE TITLE
Limit number of threads/concurrency when annotation

### ISSUE THREAD

**Issue by niyiyu** [seisbench/seisbench#68]
Hi seisbench team,

Seisbench has been very useful working with obspy stream objects, and performs well on picking and detection of traces. While a small subset of data works well regardless of concurrency and multiprocessing, it takes a long time working on a TB scale dataset with millions of streams. 

Currently, `asyncio` is used for concurrency, which is really fast. All cores of a machine are used by default. There are even potential ways to parallelize jobs within the cloud environment, as mentioned in #64. Here instead, I'm wondering if there's any way that could potentially set a limit for seisbench on a single machine? I've come up with running seisbench in a container that limit the performance from outside the docker. But I think there might be a more direct method? 

Thanks,
Yiyu

**Comment by yetinam** [comment]
Hi @niyiyu,

thanks for bringing this up. Indeed, I hadn't though about the requirement to limit the resource usage of SeisBench. May I ask, why you need to limit it? Are you running on a shared machine?

There are two aspects to the resource usage. Parallelisation within SeisBench and in the underlying libraries (numpy, pytorch). For SeisBench, users currently have no control on the level of parallelism. I think this should be address jointly with enabling higher levels of parallelism as discussed in #64. Regarding the underlying libraries, this can be configured by the user. For example, for pytorch check out this option: https://pytorch.org/docs/stable/notes/cpu_threading_torchscript_inference.html#tuning-the-number-of-threads
Which model are you using and are you running it on CPU or on GPU? Personally, when running on GPU, I experienced no CPU saturation, so I'd expect that when running the model on CPU, the main part of the load actually comes from the pytorch code. In this case `torch.set_num_threads(1)` should limit the CPU usage. Could you try that out?

**Comment by niyiyu** [comment]
Hi @yetinam,

Thanks for your reply. Indeed I am using a shared machine and by default seisbench, actually PyTorch is using all cores on the machine. Thanks for your suggestion to apply `torch.set_num_threads(1)` and actually that works for me to reduce the number of thread.

The weird thing is that suppressing the number of threads does not actually show a performance degradation. Independent tests by @zoekrauss and I show that the `computation` does not become slower with only one thread (sometimes even faster). Here I quote the computation since I am also wondering what PyTorch spends the CPU work on.

**Comment by yetinam** [comment]
Hi @niyiyu,

that's indeed a curious pattern. From what I can tell, this seems to be a CPU contention caused by synchronization. There is some discussion on this in here: https://github.com/pytorch/pytorch/issues/3146

Could you provide me a minimal code snippet to reproduce this performance issue? Then I can play around a bit with it an see if it can be solved or at least if the documentation can be supplemented with a warning.

**Comment by jawooll** [comment]
Added control for threading and more multiprocessing options with PR (#81). This should solve this enhancement issue, thanks for flagging.
