### ISSUE TITLE
Any examples for saving a model after training so it can later be loaded with from_pretrained() or similar?

### ISSUE THREAD

**Issue by alomax** [seisbench/seisbench#69]
I have been modifying `03a_training_phasenet.ipynb` (e.g. with different augmentations) and then (re)training a provided SeisBench pretrained model. But I cannot see how to save the newly trained model for later use, perhaps simply by calling `from_pretrained()`. 

I tried the simple use of:
`torch.save(model.state_dict(), PATH)`
without attempting to create the `[name].json` config file (I do not find any SeisBench code in the repository that writes the json config file.)
But this does not seem to be sufficient for later use of the trained model:

```
model_copy = sbm.PhaseNet()
model_copy.load_state_dict(torch.load(PATH))
preds = model_copy.annotate(stream)
```
seems to work, but plotting the results gives an error:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [41], in <module>
     15     if pred_class == "N":
     16         # Skip noise traces
     17         continue
---> 18     c = color_dict[pred_class]
     19     ax[i + 1].plot(offset + pred_trace.times(), pred_trace.data, label=pred_class, c=c)
     20 ax[i + 1].set_ylabel(model)

KeyError: '0'

```
Perhaps the missing `[name].json` config file is the culprit.

Is there any code or examples that show how to save a newly trained model so it can be easily used later in SeisBench in a manner similar to `from_pretrained()` for provided SeisBench pretrained models?

Thanks,
Anthony

**Comment by jawooll** [comment]
Hi Anthony,

Thanks for raising this issue, I can't seem to re-create the error as you describe above. The following code should be self-contained and load in the pre-trained model weights as you describe after saving them locally. Maybe it was just the filetype in the path which need appropriately specifying (.pt):

```python
import torch
import seisbench.models as sbm
from obspy.clients.fdsn import Client
from obspy import UTCDateTime

# Load in pre-trained PhaseNet model
pn_model = sbm.PhaseNet.from_pretrained("stead")
# Let's save the weights locally 
torch.save(pn_model.state_dict(), './abc.pt')

# Copy the model architecture
model_copy = sbm.PhaseNet()
# Load the now locally stored weights in
model_copy.load_state_dict(torch.load('./abc.pt'))

# Get a stream
client = Client("INGV")
t = UTCDateTime(2009, 4, 6, 1, 30)
stream = client.get_waveforms(network="MN", station="AQU", location="*", channel="HH?", starttime=t, endtime=t+3600)

# Make predictions on the stream and visualise
preds = model_copy.annotate(stream)
preds.plot();
```

Please let me know if this works. You do raise an important point however regarding whether we want a high-level way to save and load models which aren't in our remote cache @yetinam what do you think, is this work exploring as a minor feature addition. it would just encapsulate the above in some save / load method call.

**Comment by alomax** [comment]
Hi Jack and Jannes,

Great, thanks for the quick reply. Yes, the code of Jack works fine - I take this to confirm that I can simply use 
`torch.save(pn_model.state_dict(), PATH)`
to correctly preserve a SeisBench (re)trained model.

The problem was, as Jack noted, there is not enough information solely in the *.pt file for the advanced plotting with labeling etc, which requires the info in the json file. Adding:
`model.labels = "PSN"`
does seem to solve the plotting problem.
Currently I can copy the json file from the provided SeisBench pretrained models, presumably if I do not change them significantly. And/or I can modify/construct the json file manually, but if someone who is expert at Python json i/o has any suggestions or examples...

A a save/load method for models with arbitrary PATH (not forced to `seisbench.cache_root, "models")` sounds like the ideal solution, especially if they aid with constructing the json file.

Thanks,
Anthony

**Comment by yetinam** [comment]
Great! I'll close the issue now as the update to the documentation and the addition of a save/load function are tracked on the project page. Feel free to reopen if further problems arise.

**Comment by alomax** [comment]
Thanks!
And, "The problem was, as *Jack* noted..." should have been "The problem was, as *Jannes* noted..." - sorry!

**Comment by smyren-LANL** [comment]
Thanks for this thread! I am similarly interested in training a model, saving it, then loading it back in for evaluation at a later point. I see in the SeisBenchModel class that there are save and load methods. Save seems to work. Load, however, trips this error when I ask it to load a previously saved model. 
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[5], line 1
----> 1 m0.load(path=models/phasenet_trained](https://file+.vscode-resource.vscode-cdn.net/Users/l331294/Documents/steel_thread/stead_analysis/models/phasenet_trained)", version_str = "1", use_gpu=False)

File [/opt/anaconda3/envs/seismic/lib/python3.11/site-packages/seisbench/models/base.py:534](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/seismic/lib/python3.11/site-packages/seisbench/models/base.py:534), in SeisBenchModel.load(cls, path, version_str, use_gpu)
    532 model_args = weights_metadata.get("model_args", {})
    533 print(model_args)
--> 534 model = cls(**model_args)
    535 model._weights_metadata = weights_metadata
    536 model._parse_metadata()

TypeError: SeisBenchModel.__init__() got an unexpected keyword argument 'component_order'`

Perhaps using the above more flexible process is better, or maybe I am doing something wrong? Thanks!
