### ISSUE TITLE
Possibly incorrect filters for EQTransformer original weights

### ISSUE THREAD

**Issue by calum-chamberlain** [seisbench/seisbench#73]
In the paper describing EQTransformer the authors note that the waveforms that they trained on are "1 minute long with a sampling rate of 100 Hz and are causally band-passed filtered from 1.0-45.0 Hz". However, when loading the EQTransformer model in seisbench it looks like only a highpass of 1.0 Hz is being applied:

```python
from seisbench import models as sbm

model = sbm.EQTransformer.from_pretrained("original")
print(f"filter_args: {model.filter_args}\nfilter_kwargs: {model.filter_kwargs}")
```
filter_args: ['highpass']
filter_kwargs: {'freq': 1}

Checking the EQTransformer pre-processor code it looks like the filter that they originally applied was applied in [this line](https://github.com/smousavi05/EQTransformer/blob/7b710351c10ff973e3600313cd96bf6d21cf1d03/EQTransformer/utils/hdf5_maker.py#L180):
```python
st1.filter('bandpass',freqmin = 1.0, freqmax = 45, corners=2, zerophase=True)
```
They also apply a [cosine taper](https://github.com/smousavi05/EQTransformer/blob/7b710351c10ff973e3600313cd96bf6d21cf1d03/EQTransformer/utils/hdf5_maker.py#L181).

I tested changing the filter arguments to match those used in EQTransformer and (for one event, so not a general test) got better results, with greater picking accuracy. The main reason for pursuing this was that using the original EQTransformer model implemented in seisbench was giving good detections, but poor pick accuracy compared to (my) manual picks.

Based on that, is there a reason that the original filters are not used for the original model implemented here?

Thanks for all your work on seisBench, it is making working with these models so much simpler.

**Comment by yetinam** [comment]
Hi Calum,

thanks for point this out. There indeed seems to be a difference between our SeisBench implementation and the original. I'll add in the filter and the taper, but will likely only get to it next week. Out of curiosity, could you post a comparison plot of the performance with and without the filter and taper?

**Comment by calum-chamberlain** [comment]
I haven't implemented the taper myself, but adding in the filter makes a difference mostly for lower quality picks. For example for GeoNet event [2013p549188](https://www.geonet.org.nz/earthquake/technical/2013p549188) for station TCW changing the filter makes almost no difference.

Original highpass only filter, zoomed on P arrival:
![2013p549188_TCW_seisbench](https://user-images.githubusercontent.com/10913395/160013272-b2e90075-5a08-45b5-bc07-999f932f6955.png)

Bandpass filter 1-45 Hz, zerophase, 2 corners, zoomed on P arrival:
![2013p549188_TCW_bandpass](https://user-images.githubusercontent.com/10913395/160013390-5184d6fe-e57d-41c3-9e91-86e5c19b4519.png)

but for lower SNR arrivals (station OGWZ, same event) there is a moderate difference:

Original highpass only filter, zoomed on P arrival:
![2013p549188_OGWZ_original](https://user-images.githubusercontent.com/10913395/160013520-cd8ff89a-f7e9-4a9e-b524-3b7d0a1b61a7.png)

Bandpass filtered 1-45 Hz, zerophase, 2 corners, zoomed on P arrival:
![2013p549188_OGWZ_bandpass](https://user-images.githubusercontent.com/10913395/160013581-f2951f36-3db6-4095-8f8b-840a22dddd37.png)

As it happens, I would put the P pick closer to the seisBench highpass filtered version for OGWZ.

**Comment by yetinam** [comment]
I added the taper and updated the filter. The inconsistency with the original version should now be resolved. Please note that you'll need to delete the files `original.json` and `original.pt` from your local cache (usually `.seisbench/models/eqtransformer`). If you are running on colab (where the files are anyhow not cached permanently), this step is not necessary.

From what I saw, the difference seems to result from both the zerophase filter and the lowpass. In particular the difference between a causal and a zerophase filter leads to a small shift, which I'd say is pretty much expected.

Thanks again for making us aware of this issue!

**Comment by calum-chamberlain** [comment]
Great, thank you!
