### ISSUE TITLE
Documentation dependancies changed (doc build failing)

### ISSUE THREAD

**Issue by jawooll** [seisbench/seisbench#75]
It seems that very recently, Sphinx deprecated Jinja2 imports which now results in an ```ImportError``` when building the docs (https://github.com/sphinx-doc/sphinx/issues/10291).

Apparent fixes are to either pin the underlying Jinja2<3.1 and set it in the ```requirements.txt```, or update Sphinx. I can confirm from a local install that updating Sphinx to a later version works (4.0.3). Version pinning is pretty common (or advised) from what I can tell when building the docs but I think in this case we should update Sphinx. The reasoning being; this was a breaking change they imposed in Sphinx v4 which affected an underlying dependency and resulted in us having to make changes anyway. Let me know what you think.

**Comment by yetinam** [comment]
I agree, updating sphinx seems reasonable. I also updated the RTD theme recently due to an issue with bullet lists in the old version. As it's an issue currently causing problems with the build, I'd suggest to incorporate it in both the main and maintenance branches.

**Comment by jawooll** [comment]
Ok great, I'll add them in

**Comment by jawooll** [comment]
Doc building is passing now. 

I added to both _main_ and _maintenance_. I looked at trying the cherry-pick the commit across branches but seemed rather complex with the branches so diverged. So to be safe I just made the same change for both. Thanks for the input! closing now.
