### ISSUE TITLE
Add model weight versioning

### ISSUE THREAD

**Issue by yetinam** [seisbench/seisbench#76]
As #73 nicely showed, it might sometimes be desirable to update models weights. I'd therefore suggest to add model weight versioning. My proposal would be to keep all versions available in the repo, but by default download the latest version. Older versions can explicitly be queried using a `version` kwarg. If a version is already cached locally, checks for new versions are only performed when **explicitly initiated** by the user, for example through an argument like `check_latest`. This way, we avoid that SeisBench needs to "call home" every time `from_pretrained` is called. I think that would be a privacy issue.

#49 proposes a similar addition for datasets. However, I think versioning for models is considerably easier as the file size is much smaller.

**Comment by jawooll** [comment]
Just from my side, I think this is a good-idea. It also slightly relates to #71. We can actually integrate this into the model saving and loading once implemented, where some form of 'development' versioning can be defined for local saving. This allows for automatic model checkpointing during training.
