### ISSUE TITLE
Requesting example on fine tuning a model

### ISSUE THREAD

**Issue by JuanJose9611** [seisbench/seisbench#82]
Hi, i want to start off  by thanking you for creating and making available this  amazing tool.

I am currently working on a project and, initially, the idea was to train the EQTransformer model using data from our region of study (Jalisco, México), however after further research, the amount of data that was available seemed too small to properly train the model from the start so it was proposed to instead use transfer learning and fine tune a pre-trained EQT model. I have read both the original seisbench paper and "Wich picker fits my data?" and both seems to suggest that it is possible to do so. 

One of the example colab notebooks has an example of training PhaseNet using one of the available datasets, i was wondering if the procedure for fine tuning a model was the same as in this notebook except  using `from_pretrained` when first defining the model, or if the procedure was different.

If different:

- I was wondering if there was a resource or example of fine tuning a model using seisbench that you could share, as the only work ive done with deep learning on python was with computer vision on volcano monitoring so the tools available where a bit different.

Sorry for my bad english and thank you in advance for looking at my request.

Juan.

**Comment by yetinam** [comment]
Hey Juan,

thanks for your interest in SeisBench! Indeed, you for running transfer learning experiments, the only thing you need to change is to use `from_pretrained` for model initialisation. Otherwise, you can 1:1 use the steps from the example notebook.

You might also want to have a look at the codes for our benchmark paper: https://github.com/seisbench/pick-benchmark
While there is no transfer learning here (but you can use the same trick with `from_pretrained`), it shows one option to set up a bigger training.

I hope this answers your question. I'm closing this issue for now, but feel free to reopen if you have any further questions.

Jannes

**Comment by JuanJose9611** [comment]
Thank you for your response.

I have another question however i don't know how to reopen the issue or if i should make a new one so for now i will post it here.

Unfortunately the original idea for my thesis project had to be scraped because at the moment we do not have access to some of the data. This due to the fact that the stations that were going to be used belong to different institutions and some permisions were not given. 
Instead, we will make a catalog of seismic activity in the region using EQT and compare it with catalogs from other institutions, this idea was proposed because as of now there are several discrepancies in detections between institutions.

So far i have been playing around with one station streams  making annotation/classification with the EQT model. 
If i use more than one station per stream, as i understand, seisbench automatically separates by stations so that would be a non issue. When i use only one station and one event is detected i get one dictionary containing the detection, my question is:

- If i have two stations and there is an earthquake that is pressent on both stations, will seisbench give the two detections separately or only one?
- If the two detections are given, is there a way to assosiate using seisbench?

If you feel this question is too specific don't worry i will understand if you do not answer. 

Juan.

**Comment by yetinam** [comment]
Hey Juan,

sorry to hear about the issues with data access for your thesis! Regarding your questions, indeed, you can give SeisBench models waveforms from multiple streams at once. The output will be a list of phase picks (and in case of EQT a list of detections) at each station. However, SeisBench does not currently perform phase association, so there is no built-in way to identify which phase picks are from the same event. We are hoping to add association to SeisBench eventually but at the moment not actively working on it. Maybe @jawooll can give you further guidance on association?

Jannes

**Comment by jawooll** [comment]
Hey Juan, 

Thanks for getting back in touch. Regarding association, as Jannes says, it would be something we are considering integrating into SeisBench in the distant future, but at the moment there is no active work on implementing this functionality. 

There are a few traditional phase associators, and also machine learning-based phase associators which have open-source implementations. So once you have your picks from SeisBench, it should be pretty easy to convert them into the appropriate format and load them into an association of your choosing to detect some events. What is your study area size, teleseismic, regional, local seismicity?

If you drop you email address in here, I would be happy to provide further guidance on different associators you can use!

Cheers,
Jack

**Comment by JuanJose9611** [comment]
Thank you Jannes and Jack,

The area of study would be regional/local. 

My email is:

- juan.mcesena@alumnos.udg.mx

Juan

**Comment by JuanJose9611** [comment]
Hello again and thank you for your help!

I was looking into the newest colab notebook and it is exactly what i was looking for! I would also like to make another question.

In the notebook it is adviced to look into the GaMMA documentation for details on the `config` dictionary, however looking at [the documentation](https://wayneweiqiang.github.io/GaMMA/) it appears it only contains examples and i can't seem to find  details on parameters and such, perhaps i am not looking into the correct site?

If it is the wrong site, could you point me out to the correct link for the documentation?

Juan

**Comment by yetinam** [comment]
Hi Juan,

I admit, the documentation of GaMMA seems to be pretty minimalistic at the moment. I also didn't find much more than on the page you linked. Might be worth for you to open an issue in the GaMMA repository asking if the could provide more documentation.

Cheers,
Jannes
