### ISSUE TITLE
UrbanDenoiser integration

### ISSUE THREAD

**Issue by jawooll** [seisbench/seisbench#83]
Model extension -> [UrbanDenoiser](https://www.science.org/doi/10.1126/sciadv.abl3564?cookieSet=1).

Model compromises a transfer learning application of the original DeepDenoiser architecture for detecting sources of urban seismological noise.

**Comment by yetinam** [comment]
Conversion code added in 53a748d5083f84b8c9a3e92a2dbc792b6c1d1930.
Weight files uploaded to repo at https://repo.seisbench.org/models/deepdenoiser/
