### ISSUE TITLE
How to use local waveform data to build customize seisbench datasets? 

### ISSUE THREAD

**Issue by ZZYBian** [seisbench/seisbench#93]
If waveform data and metadata is available, how to use these local waveform data to build customize seisbench datasets?

**Comment by yetinam** [comment]
Hey @ZZYBian ,
Thanks for your interest in SeisBench. A good starting point for creating a dataset is the [respective tutorial notebook](https://colab.research.google.com/github/seisbench/seisbench/blob/main/examples/03b_creating_a_dataset.ipynb). In addition, you can look at the implementation of some of our datasets. I'd recommend for example the ETHZ dataset as a good example.

I hope this helps answering your question. Feel free to ask further questions here if you need any assistance.

**Comment by ZZYBian** [comment]
Thank you very much!
