### ISSUE TITLE
How to handle the SeisBench format dataset and modify the meta.csv according to results？

### ISSUE THREAD

**Issue by ZZYBian** [seisbench/seisbench#94]
How to use models like deepnoiser to handle custom seisbench dateset? And How to modify trace params in meta.csv according to model results？ Are there any functions that can do these right now

**Comment by yetinam** [comment]
Hey @ZZYBian ,
in general, custom datasets can be handled like the benchmark datasets. The only difference is that you load them using `sbm.WaveformDataset(path)`, where path contains the metadata.csv and waveforms.hdf5.
SeisBench datasets are generally immutable, i.e., there is no function to write a modified dataset to disc. The only option to do so is to iterate over the dataset and write it out using a WaveformDataWriter.
For the remaining question, I'm not quite sure what you are aiming for. Would you like to denoise your data and then write them to disc as a new dataset?

**Comment by ZZYBian** [comment]
Thanks for the answer!
